[TourHennire]
    name = "Tour Hennire"
    class = "intra-settlement"
    lat = 3689
    lng = 3252
    zoom_level = 2
    description = "A magnificent landmark monument that in the past used to bring people from all over the world to Hayris. Name means: Neigh Tower"
    link = ""
    from = 2
[EAMSStation5]
    name = "E.A.M.S. Station 5"
    class = "intra-settlement"
    lat = 3694
    lng = 3251
    zoom_level = 2
    description = ""
    link = ""
    from = 2
