[CielNuageux]
    name = "Ciel Nuageux"
    class = "settlement enclave"
    x = 3670
    y = 3238
    zoom_level = 1
    description = "A large cloud city that used to be the cloud half of Hayris. Name means: Cloudy Skies."
    link = ""
    from = 2