[Nimbus]
    name = "Nimbus"
    class = "settlement enclave"
    x = 3511
    y = 3105
    zoom_level = 1
    description = "An Enclave cloud city famous for its unicorns and also for being the only cloud city with a substantial amount of crystal ponies, it maintains close relations with Stratus and even controls two surface cities where its inhabitants are allowed to live. Them being Saint's Parish and Whinneapolis."
    link = ""
    from = 4
[ChiTown]
    name = "Chi Town"
    class = "settlement"
    x = 3611
    y = 2852
    zoom_level = 1
    description = "A settlement host to various tribes and former stable-ponies, controlled primarilly by the Lotus Triad."
    link = ""
    from = 3
[Filliet]
    name = "Filliet"
    class = "settlement"
    x = 3603
    y = 2855
    zoom_level = 1
    description = "A settlement litterally built over a landfill."
    link = ""
    from = 3
[Theathre]
    name = "Theathre"
    class = "settlement"
    x = 3585
    y = 2853
    zoom_level = 1
    description = "A large settlement under the protection of the M.M.M.M."
    link = ""
    from = 3
[SkyscraperStable83]
    name = "Skyscraper(Stable 83)"
    class = "settlement stable"
    x = 3524.25
    y = 3240
    zoom_level = 1
    description = "An unfinished skyscraper in the heart of Albamareal now an odd settlement. Stable 83 was constructed in the basement with access being from a ramp in the Foyer. The groups that now live in the tower have a mysterious goal of finishing the aging skyscraper."
    link = ""
    from = 13
[Raineigh]
    name = "Raineigh"
    class = "settlement enclave"
    x = 3537.375
    y = 3265.875
    zoom_level = 1
    description = "A median enclave cloud city, it was targeted during the day the bombs fell however the bomb was a dud."
    link = ""
    from = 13
[SugarGrove]
    name = "Sugar Grove"
    class = "settlement"
    x = 3533.375
    y = 3270.625
    zoom_level = 2
    description = "Once a Equestrian Naval Listening post, it was abandoned after the war, only to be rediscovered and converted into a settlement. It had been built for three weeks by the time of the story."
    link = ""
    from = 13
[TheHive]
    name = "The Hive"
    class = "settlement"
    x = 3618.75
    y = 3173.75
    zoom_level = 2
    description = "A strange deadzone area in the Toxic Valley, seems to be inhabited?"
    link = ""
    from = 13
[PortTopsailNavalBase]
    name = "Port Topsail Naval Base"
    class = "settlement steelranger"
    x = 3604.62890625
    y = 3198.2529296875
    zoom_level = 2
    description = "An old equestrian navy drydock, now owned by the Whinnychester Steel Rangers chapter."
    link = ""
    from = 13
[WhinnychesterCompound]
    name = "Whinnychester Compound"
    class = "settlement steelranger"
    x = 3513.125
    y = 3262.5
    zoom_level = 2
    description = "An old prison complex-city owned by the Whinnychester Family during the war, now a Whinnychester Steel Ranger arms factory."
    link = ""
    from = 13
[PleasantPoint]
    name = "Pleasant Point"
    class = "settlement"
    x = 3594.375
    y = 3202.125
    zoom_level = 2
    description = "The home to a poor, small town of creatures. Very dependent on the Water Caravans to sell the water from their purifiers in the river."
    link = ""
    from = 13
