[Nimbus]
    name = "Nimbus"
    class = "settlement enclave"
    x = 3511
    y = 3105
    zoom_level = 1
    description = "An Enclave cloud city famous for its unicorns and also for being the only cloud city with a substantial amount of crystal ponies, it maintains close relations with Stratus and even controls two surface cities where its inhabitants are allowed to live. Them being Saint's Parish and Whinneapolis."
    link = ""
    from = 4
[ChiTown]
    name = "Chi Town"
    class = "settlement"
    x = 3611
    y = 2852
    zoom_level = 1
    description = "A settlement host to various tribes and former stable-ponies, controlled primarilly by the Lotus Triad."
    link = ""
    from = 3
[Filliet]
    name = "Filliet"
    class = "settlement"
    x = 3603
    y = 2855
    zoom_level = 1
    description = "A settlement litterally built over a landfill."
    link = ""
    from = 3
[Theathre]
    name = "Theathre"
    class = "settlement"
    x = 3585
    y = 2853
    zoom_level = 1
    description = "A large settlement under the protection of the M.M.M.M."
    link = ""
    from = 3
[SkyscraperStable83]
    name = "Skyscraper(Stable 83)"
    class = "settlement stable"
    x = 3524.25
    y = 3240
    zoom_level = 1
    description = ""
    link = ""
    from = 13
[Raineigh]
    name = "Raineigh"
    class = "settlement enclave"
    x = 3537.375
    y = 3265.875
    zoom_level = 1
    description = ""
    link = ""
    from = 13
[SugarGrove]
    name = "Sugar Grove"
    class = "settlement"
    x = 3533.375
    y = 3270.625
    zoom_level = 2
    description = ""
    link = ""
    from = 13
[TheHive]
    name = "The Hive"
    class = "settlement"
    x = 3618.75
    y = 3173.75
    zoom_level = 2
    description = ""
    link = ""
    from = 13
[PortTopsailNavalBase]
    name = "Port Topsail Naval Base"
    class = "settlement steelranger"
    x = 3601.375
    y = 3198.125
    zoom_level = 2
    description = ""
    link = ""
    from = 13
[SandyShoals]
    name = "Sandy Shoals"
    class = "settlement"
    x = 3629.875 
    y = 3213.375
    zoom_level = 2
    description = ""
    link = ""
    from = 13

