[Nimbus]
    name = "Nimbus"
    class = "settlement enclave"
    x = 3511
    y = 3105
    zoom_level = 1
    description = "An Enclave cloud city famous for its unicorns and also for being the only cloud city with a substantial amount of crystal ponies, it maintains close relations with Stratus and even controls two surface cities where its inhabitants are allowed to live. Them being Saint's Parish and Whinneapolis."
    link = ""
    from = 4
[ChiTown]
    name = "Chi Town"
    class = "settlement"
    x = 3611
    y = 2852
    zoom_level = 1
    description = "A settlement host to various tribes and former stable-ponies, controlled primarilly by the Lotus Triad."
    link = ""
    from = 3
[Filliet]
    name = "Filliet"
    class = "settlement"
    x = 3603
    y = 2855
    zoom_level = 1
    description = "A settlement litterally built over a landfill."
    link = ""
    from = 3
[Theathre]
    name = "Theathre"
    class = "settlement"
    x = 3585
    y = 2853
    zoom_level = 1
    description = "A large settlement under the protection of the M.M.M.M."
    link = ""
    from = 3
[SkyscraperStable83]
    name = "Skyscraper(Stable 83)"
    class = "settlement stable"
    x = 3524.25
    y = 3240
    zoom_level = 1
    description = "An unfinished skyscraper in the heart of Albamareal now an odd settlement. Stable 83 was constructed in the basement with access being from a ramp in the Foyer. The groups that now live in the tower have a mysterious goal of finishing the aging skyscraper."
    link = ""
    from = 13
[Raineigh]
    name = "Raineigh"
    class = "settlement enclave"
    x = 3537.375
    y = 3265.875
    zoom_level = 1
    description = "A median enclave cloud city, it was targeted during the day the bombs fell however the bomb was a dud."
    link = ""
    from = 13
[SugarGrove]
    name = "Sugar Grove"
    class = "settlement"
    x = 3533.375
    y = 3270.625
    zoom_level = 2
    description = "Once a Equestrian Naval Listening post, it was abandoned after the war, only to be rediscovered and converted into a settlement. It had been built for three weeks by the time of the story."
    link = ""
    from = 13
[TheHive]
    name = "The Hive"
    class = "settlement"
    x = 3618.75
    y = 3173.75
    zoom_level = 2
    description = "A strange deadzone area in the Toxic Valley, seems to be inhabited?"
    link = ""
    from = 13
[PortTopsailNavalBase]
    name = "Port Topsail Naval Base"
    class = "settlement steelranger"
    x = 3604.62890625
    y = 3198.2529296875
    zoom_level = 2
    description = "An old equestrian navy drydock, now owned by the Whinnychester Steel Rangers chapter."
    link = ""
    from = 13
[WhinnychesterCompound]
    name = "Whinnychester Compound"
    class = "settlement steelranger"
    x = 3513.125
    y = 3262.5
    zoom_level = 2
    description = "An old prison complex-city owned by the Whinnychester Family during the war, now a Whinnychester Steel Ranger arms factory."
    link = ""
    from = 13
[PleasantPoint]
    name = "Pleasant Point"
    class = "settlement"
    x = 3594.375
    y = 3202.125
    zoom_level = 2
    description = "The home to a poor, small town of creatures. Very dependent on the Water Caravans to sell the water from their purifiers in the river."
    link = ""
    from = 13
[TwoRivieres]
    name = "Two Rivières"
    class = "settlement enclave"
    x = 3516.5625
    y = 3128.9140625
    zoom_level = 2
    description = "An old military base turned enclave settlement, now used to protect Fancee's and Nimbus' power source. Name means: Two Rivers."
    link = ""
    from = 14
[TheFerme]
    name = "The Ferme"
    class = "settlement"
    x = 3576.5625
    y = 3103.828125
    zoom_level = 2
    description = "A small earth pony only settlement built over an old large estate. Name means: The Farmhouse."
    link = ""
    from = 14
[Laccordeon]
    name = "L'accordéon"
    class = "settlement liberateurs"
    x = 3583.59375
    y = 3151.328125
    zoom_level = 2
    description = "A large settlement built over an accordion factory that still works!. Name means: The Accordion."
    link = ""
    from = 14
[Stable299]
    name = "Stable 299"
    class = "settlement stable"
    x = 3630.937
    y = 3104.2734375
    zoom_level = 2
    description = "An active but closed off griffon stable."
    link = ""
    from = 14
[LaGrandePlaine]
    name = "La Grande Plaine(Abri 23)"
    class = "settlement abri"
    x = 3609.375
    y = 3126.2421875
    zoom_level = 1
    description = "A large trading settlement built over the crashed remains of a D'abris Technologies Cloud Shelter. Name means: The Great Plain."
    link = ""
    from = 14
[VillageSerein]
    name = "Village Serein"
    class = "settlement liberateurs"
    x = 3630.15625
    y = 3140.9375
    zoom_level = 2
    description = "A medium sized friendly settlement built over an old medieval prench village. Name Means: Serene Village."
    link = ""
    from = 14
[QuartierDeNastha]
    name = "Quartier De Nasþa"
    class = "settlement aomielstra"
    x = 3636.875
    y = 3091.2109375 
    zoom_level = 1
    description = "A large batpony settlement built on the thestral district of Hondeaux, lead by a batpony mare named: Amiur D'Or, who has been fiercely fighting Les Libérateurs. Name means: Night District."
    link = ""
    from = 14
[ChateauXiestha]
    name = "Chateau Xiesþa"
    class = "post-war-capital aomielstra"
    x = 3584.0625
    y = 3043.859375
    zoom_level = 0
    description = "An ancient pre-equestria/pre-prance castle that once belonged to Princess Luna, it has recently been occupied by Aomielstra(Lit. Nightmare's Shadow or Nightmare's Inquisition) and is being used as their capital. The castle sits in the middle of a lake that fills up during the day and empties during the night. Name means: Midnight Castle."
    link = ""
    from = 14
[LaxThesieim]
    name = "Lax Þesieim"
    class = "settlement aomielstra"
    x = 3634.375
    y = 2965.78125
    zoom_level = 1
    description = "A large primarily unicorn settlement that allied itself and is now protected by Aomielstra, built inside an old commercial district. Name means: Place of Unicorns."
    link = ""
    from = 14
[AvenueDeLest]
    name = "Avenue de L'est"
    class = "settlement aomielstra"
    x = 3551.09375
    y = 2965.484375
    zoom_level = 1
    description = "A large naval trading settlement now controlled by Aomielstra. Name means: Eastern Avenue."
    link = ""
    from = 14
[ParcAquatique]
    name = "Parc Aquatique"
    class = "settlement"
    x = 3648.4375
    y = 3085.71875
    zoom_level = 2
    description = "A small settlement of mainly seaponies located within an old waterpark. Name means: Waterpark."
    link = ""
    from = 14
[PortMarie]
    name = "Port-Marie"
    class = "settlement liberateurs"
    x = 3661.5625
    y = 3105.4609375
    zoom_level = 1
    description = "A large naval base turned settlement featuring a docked battleship: Liberté. Name means: Port Mary."
    link = ""
    from = 14
[TourPranceExpress]
    name = "Tour Prance Express"
    class = "settlement"
    x = 3643.046875
    y = 3092.02734375
    zoom_level = 2
    description = "A small settlement of ponies who also run the TV broadcasting station for the old pre-war company Prance Express. Name means: Prance Express Tower."
    link = ""
    from = 14
[PlageDesGriffons]
    name = "Plage Des Griffons"
    class = "settlement talon"
    x = 3658.59375
    y = 3030.0546875
    zoom_level = 1
    description = "A large griffon settlement built on a large resort. Home to the Blue Talons the largest talon company in Prance. Name means: Griffon Beach."
    link = ""
    from = 14
[FortSurLaColline]
    name = "Fort Sur La Colline"
    class = "settlement steelranger"
    x = 3625.625
    y = 3051.4296875
    zoom_level = 1
    description = "A large fort now occupied by the Trottanie Steel Ranger chapter. Name means: Fort on the Hill."
    link = ""
    from = 14
[Stable255]
    name = "Stable 255"
    class = "settlement stable"
    x = 3629.375
    y = 3008.828125
    zoom_level = 1
    description = "An active zebra stable that used to trade with the outside world, but has now sealed its door thanks to the threat of Aomielstra."
    link = ""
    from = 14
[Stable277]
    name = "Stable 277"
    class = "settlement stable"
    x = 3556.40625
    y = 2945.7421875
    zoom_level = 1
    description = "An active batpony stable that is still sealed, narrowly evading discovery by Aomielstra. Its experiment was to be run like a technocracy and they were given several E.Z.P. sponsored machinery"
    link = ""
    from = 14
[AureaLilasUniversity]
    name = "Auréa Lilas University"
    class = "settlement"
    x = 3652.5
    y = 2994.7265625
    zoom_level = 2
    description = "An old prestigious university, now owned by a group of earth pony supremacists named: Ascension Terrestre."
    link = ""
    from = 14
[LaFinDuneBlague]
    name = "La Fin D'une Blague"
    class = "settlement"
    x = 3646.09375
    y = 2952.421875
    zoom_level = 2
    description = "A large settlement of gangs, talons and many other less than desired groups, built over the old town hall. Its been able to resist Aomielstran incursions. Name means: A Joke's End"
    link = ""
    from = 14
[VagueRomantique]
    name = "Vague Romantique"
    class = "settlement unity"
    x = 3536.40625
    y = 2947.5234375
    zoom_level = 2
    description = "A small secret alicorn exile settlement, contained within a high school and lead by a blue alicorn named: Chant Star. Name means: Romance Wave"
    link = ""
    from = 14
[TheDesunion]
    name = "The Désunion"
    class = "settlement unity"
    x = 3526.171875
    y = 3103.53125
    zoom_level = 2
    description = "A small alicorn exile settlement allowed to be around by the Enclave, contained within a bus station. Name means: The Dis-unity"
    link = ""
    from = 14
[LeDelta]
    name = "Le Delta"
    class = "settlement unity"
    x = 3614.84375
    y = 2926.7421875
    zoom_level = 2
    description = "A small alicorn settlement which is just getting by. Name means: The Delta"
    link = ""
    from = 14
[ColterField]
    name = "Colter Field"
    class = "settlement"
    x = 3576
    y = 2866
    zoom_level = 1
    description = "An old hoofball stadium home of the Cult of Iron Will."
    link = ""
    from = 3
[TheNascent]
    name = "The Nascent"
    class = "settlement unity"
    x = 3438.90625
    y = 3133.515625
    zoom_level = 1
    description = "A small settlement of alicorns and ponies that assist anyone crossing Le Passage, originally it helped Unity alicorns that wandered into Prance or were sent there by the Goddess."
    link = ""
    from = 3
