[ColterField]
    name = "Colter Field"
    class = "intra-settlement"
    x = 3576
    y = 2866
    zoom_level = 2
    description = "An old hoofball stadium home of the Cult of Iron Will."
    link = ""
    from = 3
[FillysTower]
    name = "Filly's Tower"
    class = "intra-settlement"
    x = 3607
    y = 2859
    zoom_level = 2
    description = "A black tall tower known for its ghost tales that scare away any scavengers. The Minotaur DJ broadcasts from here."
    link = ""
    from = 3
[ChicacoltMuseum]
    name = "Chicacolt Museum"
    class = "intra-settlement"
    x = 3590
    y = 2850
    zoom_level = 2
    description = "An old run down museum thats far too danggerous to venture into."
    link = ""
    from = 3
[FillysPier]
    name = "Filly's Pier"
    class = "intra-settlement"
    x = 3623
    y = 2853
    zoom_level = 2
    description = "An old equestrian military naval base that also featured a theme park with a ferris wheel."
    link = ""
    from = 3
[AlbamarealWestDam]
    name = "Albamareal West Dam"
    class = "misc-poi"
    x = 3520.25
    y = 3245
    zoom_level = 2
    description = "An old pre-war still functioning hydroelectric power plant on the western side of the river system."
    link = ""
    from = 13
[AlbamarealEastDam]
    name = "Albamareal East Dam"
    class = "misc-poi"
    x = 3519
    y = 3253.2
    zoom_level = 2
    description = "An old pre-war still functioning hydroelectric power plant on the eastern side of the river system."
    link = ""
    from = 13
[ToxicValley]
    name = "Toxic Valley"
    class = "misc-poi radiation"
    x = 3606.375
    y = 3176.125
    zoom_level = 2
    description = "Coated in a pasty, white radioactive layer on everything, this region is very inhospitable to all creatures. Home to some minor steel mills and industrial complex Pre-Last Day."
    link = ""
    from = 13
[NewRiverGorgeBridge]
    name = "New River Gorge Bridge"
    class = "misc-poi"
    x = 3535.125
    y = 3218.875
    zoom_level = 2
    description = "Large bridge connecting two dividing mountains and bridging the Shanandoeah river."
    link = ""
    from = 13
[EquestrianSteel]
    name = "Equestrian Seel"
    class = "intra-settlement"
    x = 3603.625
    y = 3182.875
    zoom_level = 2
    description = "The largest steel mill on the Shanandoeah river."
    link = ""
    from = 13
[LePetitCrystalTower]
    name = "Le Petit Crystal Tower"
    class = "intra-settlement enclave"
    x = 3519.0625
    y = 3107.09375
    zoom_level = 2
    description = "A smaller version of the Crystal Palace's main tower, it keeps Fancee and Nimbus warmer than the surrounding regions."
    link = ""
    from = 14
[Stable287]
    name = "Stable 287"
    class = "misc-poi stable"
    x = 3552.5
    y = 3138.1171875
    zoom_level = 2
    description = "An old mixed-pony abandoned stable where many wars seem to have been fought."
    link = ""
    from = 14
[EeztretienFacility]
    name = "Eeztretien Facility"
    class = "misc-poi ezp"
    x = 3653.4375
    y = 3155.1875
    zoom_level = 2
    description = "A huge and highly dangerous manufacturing complex owned by the ezpassionian megacorp E.Z.P. nopony has been able to loot it as its been on high alert since the bombs fell."
    link = ""
    from = 14
[Abri10]
    name = "Abri 10"
    class = "misc-poi abri"
    x = 3549.6875
    y = 3084.0859375
    zoom_level = 2
    description = "The crashed deadly remains of a D'abris Technologies Cloud Shelter, some say its still haunted by its original inhabitants."
    link = ""
    from = 14
[LesOsExcavationSite]
    name = "Les Os Excavation Site"
    class = "misc-poi radiation"
    x = 3585.46875
    y = 3118.96875
    zoom_level = 2
    description = "The deathly toxic and radioactive remains of a paleontologic excavation site from the Great War, rumours say a copy of the Black Book is buried there. Name Means: The Bones Excavation Site."
    link = ""
    from = 14
[DabrisTechnologiesHQ]
    name = "D'abris Technologies H.Q."
    class = "intra-settlement abri"
    x = 3650.46875
    y = 3098.11328125
    zoom_level = 2
    description = "The highly secure H.Q. of the pre-war corporation of D'abris Technologies(Lit. Shelter Technologies)."
    link = ""
    from = 14
[HondeauxCrater]
    name = "Hondeaux Crater"
    class = "misc-poi radiation"
    x = 3660.3125
    y = 3082.37890625
    zoom_level = 2
    description = "The impact site of Hondeaux's balefire bomb."
    link = ""
    from = 14
[ManeilleCrater]
    name = "Maneille Crater"
    class = "misc-poi radiation"
    x = 3650.46875
    y = 2973.5
    zoom_level = 2
    description = "The impact site of Maneille's balefire bomb."
    link = ""
    from = 14
[TrotluiseCrater]
    name = "Trotluise Crater"
    class = "misc-poi radiation"
    x = 3542.96875
    y = 2935.0546875
    zoom_level = 2
    description = "The impact site of Trotluise's balefire bomb."
    link = ""
    from = 14
[Arca6Wreck]
    name = "Arca 6 Wreck"
    class = "misc-poi ezp"
    x = 3653.046875
    y = 2945.7421875
    zoom_level = 2
    description = "The remains of an E.Z.P. Ark in the form a giant zeppelin, if there were any survivors they are far gone."
    link = ""
    from = 14
[MinisteredelaCooperationMillitaire]
    name = "Ministère de la Coopération Militaire"
    class = "intra-settlement"
    x = 3640
    y = 2953.015625
    zoom_level = 2
    description = "The central hub of the MCM, protected by a building shield which has not been breached since the day the bombs fell. Name means: Ministry of Military Cooperation"
    link = ""
    from = 14
[LePortariendeZeppelin]
    name = "Le Portaérien de zeppelin"
    class = "misc-poi"
    x = 3647.34375
    y = 3045.046875
    zoom_level = 2
    description = "A large military airbase primarily meant for airships, most of the ships are crashed and non functional. Name means: The Zeppelin Skyport"
    link = ""
    from = 14
[CercleMegalithique]
    name = "Cercle Mégalithique"
    class = "misc-poi aomielstra"
    x = 3592.65625
    y = 2990.2734375
    zoom_level = 2
    description = "Beyond ancient unknown ruins that are kept under tight guard of the Aomielstra. Name means: Megalithic Circles"
    link = ""
    from = 14
