[ColterField]
    name = "Colter Field"
    class = "intra-settlement"
    lat = 3576
    lng = 2866
    zoom_level = 2
    description = "An old hoofball stadium home of the Cult of Iron Will."
    link = ""
    from = ""
[FillysTower]
    name = "Filly's Tower"
    class = "intra-settlement"
    lat = 3607
    lng = 2859
    zoom_level = 2
    description = "A black tall tower known for its ghost tales that scare away any scavengers. The Minotaur DJ broadcasts from here."
    link = ""
    from = ""
[ChicacoltMuseum]
    name = "Chicacolt Museum"
    class = "intra-settlement"
    lat = 3590
    lng = 2850
    zoom_level = 2
    description = "An old run down museum thats ffar too danggerous to venture into."
    link = ""
    from = 3
[FillysPier]
    name = "Filly's Pier"
    class = "intra-settlement"
    lat = 3623
    lng = 2853
    zoom_level = 2
    description = "An old equestrian millitary naval base that also featured a theme park with a ferris wheel, "
    link = ""
    from = 3
