[ColterField]
    name = "Colter Field"
    class = "intra-settlement"
    x = 3576
    y = 2866
    zoom_level = 2
    description = "An old hoofball stadium home of the Cult of Iron Will."
    link = ""
    from = 3
[FillysTower]
    name = "Filly's Tower"
    class = "intra-settlement"
    x = 3607
    y = 2859
    zoom_level = 2
    description = "A black tall tower known for its ghost tales that scare away any scavengers. The Minotaur DJ broadcasts from here."
    link = ""
    from = 3
[ChicacoltMuseum]
    name = "Chicacolt Museum"
    class = "intra-settlement"
    x = 3590
    y = 2850
    zoom_level = 2
    description = "An old run down museum thats ffar too danggerous to venture into."
    link = ""
    from = 3
[FillysPier]
    name = "Filly's Pier"
    class = "intra-settlement"
    x = 3623
    y = 2853
    zoom_level = 2
    description = "An old equestrian millitary naval base that also featured a theme park with a ferris wheel."
    link = ""
    from = 3
[AlbamarealWestDam]
    name = "Albamareal West Dam"
    class = "misc-poi"
    x = 3520.25
    y = 3245
    zoom_level = 2
    description = ""
    link = ""
    from = 13
[AlbamarealEastDam]
    name = "Albamareal East Dam"
    class = "misc-poi"
    x = 3519
    y = 3253.2
    zoom_level = 2
    description = ""
    link = ""
    from = 13
[WhinnychesterCompound]
    name = "Whinnychester Compound"
    class = "misc-poi"
    x = 3513.125
    y = 3262.5
    zoom_level = 2
    description = ""
    link = ""
    from = 13
[PleasantPoint]
    name = "Pleasant Point"
    class = "misc-poi"
    x = 3594.375
    y = 3202.125
    zoom_level = 2
    description = ""
    link = ""
    from = 13
[ToxicValley]
    name = "Toxic Valley"
    class = "misc-poi radiation"
    x = 3606.375
    y = 3176.125
    zoom_level = 2
    description = ""
    link = ""
    from = 13
[NewRiverGorgeBridge]
    name = "New River Gorge Bridge"
    class = "misc-poi"
    x = 3535.125
    y = 3218.875
    zoom_level = 2
    description = ""
    link = ""
    from = 13
[EquestrianStreet]
    name = "Equestrian Street"
    class = "intra-settlement"
    x = 3603.625
    y = 3182.875
    zoom_level = 2
    description = ""
    link = ""
    from = 13
