[FabricaDeBatatas]
    name = "Fábrica de Batatas"
    class = "misc-poi"
    lat = 2977
    lng = 2989
    zoom_level = 2
    description = "An old massive potato factory, it kinda smells. Name means: Potato Factory."
    link = ""
    from = 2
[MansaoCarangueijo]
    name = "Mansão Carangueijo"
    class = "misc-poi"
    lat = 3007
    lng = 3024
    zoom_level = 2
    description = "Also known as Crab Manor, an old seapony manor."
    link = ""
    from = 2