[Estebordoburgo]
    name = "Estebordoburgo"
    class = "settlement"
    x = 3004
    y = 3019
    zoom_level = 2
    description = "'This is how its supposed to be spelled!'"
    link = ""
    from = 2