[Metro]
    name = "Metrô"
    class = "settlement"
    x = 2978
    y = 2867
    zoom_level = 2
    description = "A large settlement built on the safest parts of the former Thalesian Metro System. Name means: Metro."
    link = ""
    from = 2
[Trilhao]
    name = "Trilhão"
    class = "settlement"
    x = 2989
    y = 2856
    zoom_level = 2
    description = "A small settlement built over a former thalesian raill station. Name means: Trillions of Rail."
    link = ""
    from = 2
[VistasDosTrilhos]
    name = "Vistas dos Trilhos"
    class = "settlement"
    x = 3000
    y = 2855
    zoom_level = 1
    description = "A bustling trade settlement and the largest in Ezthalesia that was built over a large rail yard and train factory, both of which have been reactivated which is what lead to its boom. Name means: Views of the Rails."
    link = ""
    from = 2
[Barcopolis]
    name = "Barcópolis"
    class = "settlement"
    x = 3019
    y = 2861
    zoom_level = 2
    description = "A small coastal settlement built over a former luxury yatch pier. Name means: Boat City."
    link = ""
    from = 2
[Fuligem]
    name = "Fuligem"
    class = "settlement"
    x = 3035
    y = 2873
    zoom_level = 2
    description = "A small settlement built over the remains of an Ark that was a train. Name means: Smoke."
    link = ""
    from = 2
[PortoGrande]
    name = "Porto Grande"
    class = "settlement"
    x = 3049
    y = 2876
    zoom_level = 1
    description = "A large trading settlement that boasts of a fleet of tugboats and a cargo ship. Name means: Great Port."
    link = ""
    from = 2
[MinasDouro]
    name = "Minas D'ouro"
    class = "settlement"
    x = 3014
    y = 2899
    zoom_level = 2
    description = "A small settlement built over a deactivated historical gold mine. Name means: Gold Mine."
    link = ""
    from = 2
[CampoLua]
    name = "Campo Lua"
    class = "settlement"
    x = 3002
    y = 2873
    zoom_level = 2
    description = "A medium settlement made up primarilly of scout fillies and colts. Name means: Camp Moon."
    link = ""
    from = 2
[Precinto]
    name = "Precinto"
    class = "settlement"
    x = 2982
    y = 2901
    zoom_level = 2
    description = "A medium settlement built over Thalesia's former high security prison. Name means: Precinct"
    link = ""
    from = 2
[TresPredios]
    name = "Três Prédios"
    class = "settlement"
    x = 2965
    y = 2893
    zoom_level = 2
    description = "A medium primarilly cloud based settlement built over 3 large skyscrapers that tilted and coollided with each other. Name means: Three Buildings."
    link = ""
    from = 2
[Fabriquicia]
    name = "Fabriquícia"
    class = "settlement"
    x = 2934
    y = 2894
    zoom_level = 2
    description = "A small settlement built over an old car factory. Name means: Little Factory."
    link = ""
    from = 2
[CascadasSerenas]
    name = "Cascadas Serênas"
    class = "settlement"
    x = 2988
    y = 2886
    zoom_level = 2
    description = "A small kirin settlement, remote from much of anything at the summt of the Peak of Thales where the Águas Cristalinas(Crystal Waters) river begins. Name means: Serene Waterfalls."
    link = ""
    from = 2
[ThalesiaDowntown]
    name = "Thalesia Downtown"
    class = "settlement"
    x = 2974
    y = 2901
    zoom_level = 1
    description = "A collection of settlements that form a large one built over Thalesia's historical downtown."
    link = ""
    from = 2
