[Frizer]
    name = "Frizer"
    class = "settlement"
    lat = 2921
    lng = 2972
    zoom_level = 2
    description = "The only settlement in Starynopla, made up of ghouls and it hardly interacts with the outside. It was built on an old cryogenics facility. Name means: (Misspelled)Freezer."
    link = ""
    from = 2
