[PalacioTenebrae]
    name = "Palácio Tenebrae"
    class = "intra-settlement"
    x = 2941 
    y = 2984
    zoom_level = 2
    description = "The former royal palace of Queen Starya. Untouched since the end of The Great War. Name means: Tenebrae Palace."
    link = ""
    from = 2
[ElevadorEspacialKatarya]
    name = "Elevador Espacial Katarya Tenebrae Çari Skarya"
    class = "intra-settlement"
    x = 2944
    y = 2974
    zoom_level = 2
    description = "The world's still standing tallest creature-made building, formerly used to transport things to space without the need of rockets and a 'symbol of peace, cooperation and prosperity. Name means: Space Elevator Katarya Tenebrae Çari Skarya."
    link = ""
    from = 2
[TorreCapital]
    name = "Torre Capital"
    class = "intra-settlement"
    x = 2934
    y = 2968
    zoom_level = 2
    description = "One of the tallest towers in the world it used to be used to broadcast the Corporação de Telecomunicações de Ezpassiôn(Ezpassion Telecomunications Corporation) signal and is still doing so. Name means: Capital Tower."
    link = ""
    from = 2
[Eterno]
    name = "Eterno"
    class = "intra-settlement"
    x = 2922
    y = 2954
    zoom_level = 2
    description = "The world's tallest skyscraper with 1000000 storeys, barely standing with several floors that have collapsed downwards partially. Name means: Eternal."
    link = ""
    from = 2
[BaiaBelaVista]
    name = "Baía Bela Vista"
    class = "intra-settlement"
    x = 2912
    y = 2961
    zoom_level = 2
    description = "The world's deepest structure, nobody knows how deep it actually goes or what its true purpose is, its said to be some sort of prison. Name means: Beautyful View Bay."
    link = ""
    from = 2
