[Hope]
    name = "Hope"
    class = "settlement redeye"
    x = 3261
    y = 3278
    zoom_level = 2
    description = "A small settlement by Ponyville."
    link = "https://falloutequestria.fandom.com/wiki/Hope"
    from = 0
[Cathedral]
    name = "Cathedral (Stable 101)"
    class = "post-war-capital stable"
    x = 3225
    y = 3340
    zoom_level = 0
    description = "The capital of <a href='https://falloutequestria.fandom.com/wiki/Red_Eye%27s_Army'>Red Eye's empire</a> built over his old stable."
    link = "https://falloutequestria.fandom.com/wiki/The_Cathedral"
    from = 0
[Stable39]
    name = "Stable 39"
    class = "settlement stable"
    x = 3328
    y = 3452
    zoom_level = 2
    description = "Lirah Scratch's and Lightning Orange's still active stable."
    link = ""
    from = 2
[Stable2]
    name = "Stable 2"
    class = "settlement stable"
    x = 3256
    y = 3302
    zoom_level = 2
    description = "<a href='https://falloutequestria.fandom.com/wiki/Littlepip'>Littlepip</a>'s and <a href='https://falloutequestria.fandom.com/wiki/Velvet_Remedy'>Velvet Remedy</a>'s stable and also one of the larger still active stables."
    link = "https://falloutequestria.fandom.com/wiki/Stable_2"
    from = 0
[JunctionR7]
    name = "Junction R-7"
    class = "settlement"
    x = 3306
    y = 3351
    zoom_level = 1
    description = "A medium settlement and Talon camp."
    link = "https://falloutequestria.fandom.com/wiki/Junction_R-7"
    from = 0
[ShatteredHoof]
    name = "Shattered Hoof Re-Education Facility"
    class = "settlement redeye"
    x = 3298
    y = 3368
    zoom_level = 2
    description = "A pre-war facility to hold political prisioners."
    link = "https://falloutequestria.fandom.com/wiki/Shattered_Hoof_Re-Education_Facility"
    from = 0
[NewAppleloosa]
    name = "New Appleloosa"
    class = "settlement"
    x = 3283
    y = 3269
    zoom_level = 1
    description = "A small settlement built over a rail yard."
    link = "https://falloutequestria.fandom.com/wiki/New_Appleloosa"
    from = 0
[TheRepublic]
    name = "The Republic"
    class = "settlement"
    x = 3343
    y = 3296
    zoom_level = 1
    description = "A small settlement constantly under attack by raiders."
    link = "https://falloutequestria.fandom.com/wiki/The_Republic"
    from = 0
[Glyphmark]
    name = "Glyphmark"
    class = "settlement"
    x = 3388
    y = 3232
    zoom_level = 1
    description = "A small zebra settlement and home of Xenith's daughter: Xephyr"
    link = "https://falloutequestria.fandom.com/wiki/Glyphmark"
    from = 0
[Fetlock]
    name = "Fetlock"
    class = "settlement redeye"
    x = 3304
    y = 3486
    zoom_level = 1
    description = "Fetlock are what remains of the suburbs of Manehatten, its a pseudo-settlement."
    link = "https://falloutequestria.fandom.com/wiki/Fetlock"
    from = 0
[FriendshipCity]
    name = "Friendship City"
    class = "settlement"
    x = 3258
    y = 3535
    zoom_level = 1
    description = "A large settlement built within the Pony of Liberty Statue.<p><img src='https://static.wikia.nocookie.net/falloutequestria/images/d/da/Fallout_equestria_factions_friendship_city_by_dotrook-d4knqyy.png' style='height: 160px;'></img></p> <p>Image by: DotRook</p>"
    link = "https://falloutequestria.fandom.com/wiki/Friendship_City"
    from = 0
[TenponyTower]
    name = "Tenpony Tower"
    class = "settlement"
    x = 3287
    y = 3530
    zoom_level = 1
    description = "A bustling settlement of wealthy ponies built within an old Ministry of Arcane Sciences Hub home to the Twilight Society. <p><img src='https://static.wikia.nocookie.net/falloutequestria/images/d/dd/Tenpony_tower_by_masterjosh140_copy.jpg' style='height: 160px;'></img></p> <p>Image by: MasterJosh140</p><img src='https://static.wikia.nocookie.net/falloutequestria/images/7/77/Twilight_Society.png' style='height: 160px;'></img> Image by: DotRook"
    link = "https://falloutequestria.fandom.com/wiki/Tenpony_Tower"
    from = 0
[Gutterville]
    name = "Gutterville"
    class = "settlement"
    x = 3292
    y = 3539
    zoom_level = 1
    description = "A small settlement in manehattan."
    link = "https://falloutequestria.fandom.com/wiki/Gutterville"
    from = 0
[Arbu]
    name = "Arbu"
    class = "settlement"
    x = 3274
    y = 3521
    zoom_level = 2
    description = "A very... strange small settlement.<img src='https://static.wikia.nocookie.net/falloutequestria/images/1/13/Fallout_equestria_factions_arbu_by_dotrook-d4knv89.png' style='height: 160px;'></img> Image by: DotRook"
    link = "https://falloutequestria.fandom.com/wiki/Arbu"
    from = 0
[BucklinCross]
    name = "Buckling Cross"
    class = "settlement steelranger"
    x = 3277
    y = 3526
    zoom_level = 1
    description = "The base of the Manehattan Steel Rangers branch.<p><img src='https://static.wikia.nocookie.net/falloutequestria/images/a/ab/Bucklyn_cross_by_maeni.jpg' style='height: 160px;'></img></p> <p>Image by: maeni</p><img src='https://static.wikia.nocookie.net/falloutequestria/images/8/84/Steelrangersfactiondotrook.png' style='height: 160px;'></img> Image by: DotRook"
    link = "https://falloutequestria.fandom.com/wiki/Bucklyn_Cross"
    from = 0
[Duskhoof]
    name = "Duskhoof"
    class = "settlement redeye"
    x = 3310
    y = 3524
    zoom_level = 1
    description = "A small settlement of batponies."
    link = ""
    from = 3
[RaidersNest]
    name = "Raider's Nest"
    class = "settlement redeye"
    x = 3321
    y = 3516
    zoom_level = 1
    description = "A nest of raiders vaguelly settlement shaped."
    link = ""
    from = 0
[Neighvarro]
    name = "Neighvarro"
    class = "settlement enclave"
    x = 3408
    y = 3220
    zoom_level = 1
    description = "The Enclave's most millitarilly capable city and could've become its capital.<img src='https://static.wikia.nocookie.net/falloutequestria/images/3/39/Grand_Pegasus_Enclave.png' style='height: 160px;'></img> Image by: DotRook"
    link = "https://falloutequestria.fandom.com/wiki/Neighvarro"
    from = 0
[Stable1City]
    name = "Stable (1) City"
    class = "settlement stable"
    x = 3411
    y = 3275
    zoom_level = 1
    description = "A settlement of mainly pink cloud ghouls."
    link = "https://falloutequestria.fandom.com/wiki/Stable_City"
    from = 0
[ShatteredHoofMine]
    name = "Shattered Hoof Mine"
    class = "settlement talon"
    x = 3338
    y = 3377
    zoom_level = 1
    description = "A medium settlement of griffons ran by a griffon named <a href='https://falloutequestria.fandom.com/wiki/Gawdyna_Grimfeathers'>Gawdyna Grimfeathers</a>."
    link = ""
    from = 0
[Maripony]
    name = "Maripony"
    class = "settlement unity"
    x = 3246
    y = 3247
    zoom_level = 1
    description = "An old wartime research facility owned by the M.A.S. it houses the Alicorn Project and nowadays the Goddess.<p><img src='https://static.wikia.nocookie.net/falloutequestria/images/1/17/Maripony.png' style='height: 160px;'></img></p> <p>Image by: OmegaRidley</p>"
    link = "https://falloutequestria.fandom.com/wiki/Maripony"
    from = 0
[EquestriaRoyalPalace]
    name = "Equestrian Royal Palace"
    class = "settlement unity"
    x = 3415
    y = 3277
    zoom_level = 2
    description = "Or Canterlot Castle, it was the old home of the equestrian princesses, nowadays it seems to be controlled by a crazed alicorn named Nightseer."
    link = "https://falloutequestria.fandom.com/wiki/Canterlot_Castle"
    from = 0
[LaxIenThesiela]
    name = "Laxieran Ien Þesiela"
    class = "settlement"
    x = 3285.15625
    y = 3516.3359375
    zoom_level = 2
    description = "A small settlement of batponies built on an old orphanage, has evaded Red Eye control by paying tribute. Lead by a batpony mare named Night Heart, the settlement's mayor. Name means: Home of the Batpony."
    link = ""
    from = 2
