[IronshodFirearms]
    name = "Ironshod Firearms"
    class = "misc-poi"
    lat = 3281
    lng = 3306
    zoom_level = 2
    description = "An old weapon's manufacturing plant."
    link = "https://falloutequestria.fandom.com/wiki/Ironshod_Firearms"
    from = 0
[OldOlneigh]
    name = "Old Olneigh"
    class = "misc-poi"
    lat = 3250
    lng = 3252
    zoom_level = 2
    description = "An old wartime village."
    link = "https://falloutequestria.fandom.com/wiki/Old_Olneigh"
    from = 0
[Maripony]
    name = "Maripony"
    class = "misc-poi"
    lat = 3246
    lng = 3247
    zoom_level = 1
    description = "An old wartime research facility owned by the M.A.S. it houses the Alicorn project and nowdays the Goddess.<p><img src='https://static.wikia.nocookie.net/falloutequestria/images/1/17/Maripony.png' style='height: 160px;'></img></p> <p>Image by: OmegaRidley</p>"
    link = "https://falloutequestria.fandom.com/wiki/Maripony"
    from = 0
[Stable24]
    name = "Stable 24"
    class = "misc-poi stable"
    lat = 3292
    lng = 3282
    zoom_level = 2
    description = "A dead stable that, unlike most others had an overstallion."
    link = "https://falloutequestria.fandom.com/wiki/Stable_24"
    from = 0
[PinkiePieMuseum]
    name = "Pinkie Pie Museum"
    class = "misc-poi"
    lat = 3290
    lng = 3333
    zoom_level = 2
    description = "The old Ministry of Morale's museum."
    link = "https://falloutequestria.fandom.com/wiki/Pinkie_Pie_Museum"
    from = 0
[HippocampusEnergyPlant12]
    name = "Hippocampus Energy Plant 12"
    class = "misc-poi"
    lat = 3305
    lng = 3407
    zoom_level = 2
    description = "An old energy plant."
    link = ""
    from = 0
[LumenContaintmentFacility]
    name = "Lumen Containment Facility"
    class = "misc-poi ezp"
    lat = 3365
    lng = 3411
    zoom_level = 1
    description = "An old wartime facility built into a mountain, it was built to contain an ancient zebra ruin, for whatever reason. It features a very very very large E.Z.P. branded Seal Door."
    link = ""
    from = 2
[Arca1Wreck]
    name = "Arca 1 Wreck"
    class = "misc-poi ezp"
    lat = 3427
    lng = 3367
    zoom_level = 2
    description = "The wreck of Ezpassion's first Ark, it housed its main political leaders and influential V.I.P.s."
    link = ""
    from = 2
[EAMSHub]
    name = "E.A.M.S. Hub"
    class = "intra-settlement eams"
    lat = 3408
    lng = 3273
    zoom_level = 2
    description = "The hub of the Equestrian Arm of Movement System for very important ponies!"
    link = ""
    from = 2
[EAMSStation2]
    name = "E.A.M.S. Station 2"
    class = "intra-settlement eams"
    lat = 3341
    lng = 3449
    zoom_level = 2
    description = ""
    link = ""
    from = 2
[Stable29]
    name = "Stable 29"
    class = "misc-poi stable"
    lat = 3301
    lng = 3496
    zoom_level = 2
    description = "A dead stable that was entirelly controlled by robots."
    link = "https://falloutequestria.fandom.com/wiki/Stable_29"
    from = 0
[RedRacerFactory]
    name = "Red Racer Factory"
    class = "intra-settlement"
    lat = 3293
    lng = 3507
    zoom_level = 2
    description = "The main factory of the Red Racer Corporation."
    link = ""
    from = 0
[ManehattanCrater]
    name = "Manehattan Crater"
    class = "misc-poi"
    lat = 3275
    lng = 3538
    zoom_level = 1
    description = "The impact site of the bomb that struck Manehattan."
    link = ""
    from = 0
[HorseshoeTower]
    name = "Horseshoe Tower"
    class = "intra-settlement"
    lat = 3310
    lng = 3509
    zoom_level = 2
    description = "An old tall skyscraper."
    link = ""
    from = 0
[CelestiaLine]
    name = "Celestia Line"
    class = "intra-settlement"
    lat = 3303
    lng = 3518
    zoom_level = 2
    description = "Manehattan's major monorail line."
    link = "https://falloutequestria.fandom.com/wiki/Celestia_Line"
    from = 0
[LunaLine]
    name = "Luna Line"
    class = "intra-settlement"
    lat = 3299
    lng = 3510
    zoom_level = 2
    description = "Manehattan's second major monorail line."
    link = "https://falloutequestria.fandom.com/wiki/Luna_Line"
    from = 0
[GRAS]
    name = "G.R.A.S."
    class = "intra-settlement"
    lat = 3270
    lng = 3531
    zoom_level = 2
    description = "Manehattan's zoo."
    link = ""
    from = 0
[ManehattanGardens]
    name = "Manehattan Gardens"
    class = "intra-settlement"
    lat = 3301
    lng = 3527
    zoom_level = 1
    description = "A pre-wat wildlife sanctuary."
    link = "https://falloutequestria.fandom.com/wiki/Manehattan_Gardens"
    from = 0
[FourStarsGrandHotel]
    name = "Four Stars Grand Hotel"
    class = "intra-settlement"
    lat = 3293
    lng = 3523
    zoom_level = 2
    description = "A major hotel in Manehattan, now a ruin."
    link = ""
    from = 0
[HopeSolarArray]
    name = "Hope Solar Array"
    class = "misc-poi"
    lat = 3259
    lng = 3283
    zoom_level = 3
    description = "The solar array that powered Ponyville, now mostly useless thanks to the cloud cover."
    link = ""
    from = 0
[GhostFarm]
    name = "Ghost Farm"
    class = "intra-settlement"
    lat = 3259
    lng = 3293
    zoom_level = 3
    description = "A farm where its said that anyone who ventures into it never returns."
    link = "https://falloutequestria.fandom.com/wiki/Haunted_Farm"
    from = 0
[ZecorasHut]
    name = "Zecora's Hut"
    class = "intra-settlement"
    lat = 3251
    lng = 3299
    zoom_level = 3
    description = "The hut of the zebra Zecora."
    link = "https://falloutequestria.fandom.com/wiki/Zecora's_Hut"
    from = 1
[CarouselBoutique]
    name = "Carousel Boutique"
    class = "intra-settlement"
    lat = 3261
    lng = 3299
    zoom_level = 3
    description = "Rarity's old shop."
    link = "https://falloutequestria.fandom.com/wiki/Carousel_Boutique"
    from = 1
[SweetAppleAcres]
    name = "Sweet Apple Acres"
    class = "intra-settlement"
    lat = 3259
    lng = 3303
    zoom_level = 3
    description = "Applejack's old farm<p><img src='https://static.wikia.nocookie.net/falloutequestria/images/1/13/SweetAppleAcres.jpg' style='height: 120px;'></img></p> <p>Image by: MLP.</p>"
    link = "https://falloutequestria.fandom.com/wiki/Sweet_Apple_Acres"
    from = 1
[PonyvilleLibrary]
    name = "Ponyville Library"
    class = "intra-settlement"
    lat = 3266
    lng = 3292
    zoom_level = 3
    description = "Twilight Sparkles' old library."
    link = ""
    from = 0
[FluttershysCabin]
    name = "Fluttershy's Cabin"
    class = "intra-settlement"
    lat = 3264
    lng = 3305
    zoom_level = 3
    description = "Fluttershy's old home."
    link = "https://falloutequestria.fandom.com/wiki/Fluttershy's_Cabin"
    from = 0
[MacintoshMemorial]
    name = "Macintosh Memorial"
    class = "intra-settlement"
    lat = 3270
    lng = 3294
    zoom_level = 3
    description = "A memorial for Big Macintosh, one of Equestria's war heroes."
    link = "https://falloutequestria.fandom.com/wiki/The_Macintosh_War_Memorial"
    from = 0
[RainbowDashsShack]
    name = "Rainbow Dash's Shack"
    class = "misc-poi"
    lat = 3296
    lng = 3316
    zoom_level = 2
    description = "The old secluded wartime get-away of Rainbow Dash."
    link = "https://falloutequestria.fandom.com/wiki/Rainbow_Dash%27s_Shack"
    from = 0
[EquestriaRoyalPalace]
    name = "Equestrian Royal Palace"
    class = "intra-settlement"
    lat = 3415
    lng = 3277
    zoom_level = 3
    description = "Or Canterlot Castle, it was the old home of the equestrian princesses, nowdays it seems to be controlled by a crazed alicorn named Nightseer."
    link = "https://falloutequestria.fandom.com/wiki/Canterlot_Castle"
    from = 0
[MinistryWalk]
    name = "Ministry Walk"
    class = "intra-settlement"
    lat = 3416
    lng = 3276
    zoom_level = 3
    description = "The old plaza where the main buildings of each equestrian ministry are located."
    link = "https://falloutequestria.fandom.com/wiki/Ministry_Walk"
    from = 0
[CelestianMonument]
    name = "Celestian Monument"
    class = "intra-settlement"
    lat = 3417
    lng = 3277
    zoom_level = 3
    description = "A landmark in honour of Princess Celestia's thousand year long reign."
    link = "https://falloutequestria.fandom.com/wiki/Celestian_Monument"
    from = 0
[IvoryTower]
    name = "Ivory Tower"
    class = "intra-settlement"
    lat = 3418
    lng = 3279
    zoom_level = 3
    description = "A litteral ivory tower, damn canterlot elites!"
    link = "https://falloutequestria.fandom.com/wiki/Ivory_Tower"
    from = 0
[SchoolForGiftedUnicorns]
    name = "School For Gifted Unicorns"
    class = "intra-settlement"
    lat = 3417
    lng = 3274
    zoom_level = 3
    description = "A pre-war magic academy for unicorns ran by Princess Celestia."
    link = "https://falloutequestria.fandom.com/wiki/Princess_Celestia's_School_for_Gifted_Unicorns"
    from = 0
[SphinxQuicksilverRuin]
    name = "Sphinx Quicksilver Ruin"
    class = "misc-poi"
    lat = 3447
    lng = 3374
    zoom_level = 2
    description = "A set of VERY ANCIENT sphinx ruins with many pools of quicksilver."
    link = ""
    from = 2
[HMBLunaria]
    name = "HMB Lunaria"
    class = "intra-settlement"
    lat = 3429
    lng = 3365
    zoom_level = 2
    description = "An old broken submarine left there by the Enclave and now used as Splendid Fall's town hall."
    link = ""
    from = 2
[SphinxTown]
    name = "Sphinx Town"
    class = "intra-settlement"
    lat = 3440
    lng = 3369
    zoom_level = 2
    description = "The part of Splendid Falls where all the sphinxes have started to live and may or may not be erecting a pyramid."
    link = ""
    from = 2
[FleurDeLisGreatBoutique]
    name = "Fleur De Lis' Great Boutique"
    class = "intra-settlement armour"
    lat = 3435
    lng = 3373
    zoom_level = 2
    description = "The ghoul's magnificent clothes and armours shop."
    link = ""
    from = 2
[OldBatopia]
    name = "Old Batopia"
    class = "intra-settlement"
    lat = 3438
    lng = 3355
    zoom_level = 2
    description = "An old pre-war batpony city that once had a serenity induced time loop anomaly."
    link = ""
    from = 2
[EZPStoreSplendid]
    name = "E.Z.P. Store (Splendid Falls)"
    class = "intra-settlement ezp"
    lat = 3431
    lng = 3376
    zoom_level = 2
    description = "'E.Z.P. We make your life magnificently better!'"
    link = ""
    from = 2
[AetherithsWeapons]
    name = "Aetherith's Weapons"
    class = "intra-settlement weapons"
    lat = 3433
    lng = 3366
    zoom_level = 2
    description = "A weapon store owned by the zebra Aetherith, sister of Zephyrith."
    link = ""
    from = 2
[NewStableDistrict]
    name = "New Stable District"
    class = "intra-settlement"
    lat = 3431
    lng = 3360
    zoom_level = 2
    description = "Where the ponies of stable 152 erected an entirely new city block."
    link = ""
    from = 2
[SplendidMedicalDistrict]
    name = "Splendid Medical District"
    class = "intra-settlement medical"
    lat = 3436
    lng = 3370
    zoom_level = 2
    description = "A growing collection of medical staff."
    link = ""
    from = 2
[SniezhanniamEmbassy]
    name = "Sniezhannia Embassy"
    class = "intra-settlement"
    lat = 3437
    lng = 3375
    zoom_level = 2
    description = "The official embassy between Splendid Falls and the Sniezhannia S.S.R."
    link = ""
    from = 2
[LightOfTheMoonGeneralGoods]
    name = "Light Of The Moon General Goods"
    class = "intra-settlement shop"
    lat = 3431.875
    lng = 3372.4375
    zoom_level = 2
    description = "A general store owned by a unicorn named Sunflower."
    link = ""
    from = 2
