[Hope]
    name = "Hope"
    class = "settlement"
    lat = 3261
    lng = 3278
    zoom_level = 2
    description = "A small settlement by Ponyville."
    link = "https://falloutequestria.fandom.com/wiki/Hope"
    from = 0
[Cathedral]
    name = "Cathedral (Stable 101)"
    class = "post-war-capital"
    lat = 3225
    lng = 3340
    zoom_level = 0
    description = "The capital of <a href='https://falloutequestria.fandom.com/wiki/Red_Eye%27s_Army'>Red Eye's empire</a> built over his old stable."
    link = "https://falloutequestria.fandom.com/wiki/The_Cathedral"
    from = 0
[Stable39]
    name = "Stable 39"
    class = "settlement"
    lat = 3328
    lng = 3452
    zoom_level = 2
    description = "Lirah Scratch's and Lightning Orange's still active stable."
    link = ""
    from = 2
[Stable2]
    name = "Stable 2"
    class = "settlement"
    lat = 3256
    lng = 3302
    zoom_level = 2
    description = "<a href='https://falloutequestria.fandom.com/wiki/Littlepip'>Littlepip</a>'s and <a href='https://falloutequestria.fandom.com/wiki/Velvet_Remedy'>Velvet Remedy</a>'s stable and also one of the larger still active stables."
    link = "https://falloutequestria.fandom.com/wiki/Stable_2"
    from = 0
[JunctionR7]
    name = "Junction R-7"
    class = "settlement"
    lat = 3306
    lng = 3351
    zoom_level = 1
    description = "A medium settlement and Talon camp."
    link = "https://falloutequestria.fandom.com/wiki/Junction_R-7"
    from = 0
[ShatteredHoof]
    name = "Shattered Hoof Re-Education Facility"
    class = "settlement"
    lat = 3298
    lng = 3368
    zoom_level = 2
    description = "A pre-war facility to hold political prisioners."
    link = "https://falloutequestria.fandom.com/wiki/Shattered_Hoof_Re-Education_Facility"
    from = 0
[NewAppleloosa]
    name = "New Appleloosa"
    class = "settlement"
    lat = 3283
    lng = 3269
    zoom_level = 1
    description = "A small settlement built over a rail yard."
    link = "https://falloutequestria.fandom.com/wiki/New_Appleloosa"
    from = 0
[TheRepublic]
    name = "The Republic"
    class = "settlement"
    lat = 3343
    lng = 3296
    zoom_level = 1
    description = "A small settlement constantly under attack by raiders."
    link = "https://falloutequestria.fandom.com/wiki/The_Republic"
    from = 0
[Glyphmark]
    name = "Glyphmark"
    class = "settlement"
    lat = 3388
    lng = 3232
    zoom_level = 1
    description = "A small zebra settlement and home of Xenith's daughter: Xephyr"
    link = "https://falloutequestria.fandom.com/wiki/Glyphmark"
    from = 0
[Fetlock]
    name = "Fetlock"
    class = "settlement"
    lat = 3304
    lng = 3486
    zoom_level = 1
    description = "Fetlock are what remains of the suburbs of Manehatten, its a pseudo-settlement."
    link = "https://falloutequestria.fandom.com/wiki/Fetlock"
    from = 0
[FriendshipCity]
    name = "Friendship City"
    class = "settlement"
    lat = 3258
    lng = 3535
    zoom_level = 1
    description = "A large settlement built within the Pony of Liberty Statue."
    link = "https://falloutequestria.fandom.com/wiki/Friendship_City"
    from = 0
[TenponyTower]
    name = "Tenpony Tower"
    class = "settlement"
    lat = 3287
    lng = 3530
    zoom_level = 1
    description = "A bustling settlement of wealthy ponies built within an old Ministry of Arcane Sciences Hub. <p><img src='https://static.wikia.nocookie.net/falloutequestria/images/d/dd/Tenpony_tower_by_masterjosh140_copy.jpg' style='height: 160px;'></img></p> <p>Image by: MasterJosh140</p>"
    link = "https://falloutequestria.fandom.com/wiki/Tenpony_Tower"
    from = 0
[Gutterville]
    name = "Gutterville"
    class = "settlement"
    lat = 3292
    lng = 3539
    zoom_level = 1
    description = "A small settlement in manehattan."
    link = "https://falloutequestria.fandom.com/wiki/Gutterville"
    from = 0
[Arbu]
    name = "Arbu"
    class = "settlement"
    lat = 3274
    lng = 3521
    zoom_level = 2
    description = "A very... strange small settlement.<img src='https://static.wikia.nocookie.net/falloutequestria/images/1/13/Fallout_equestria_factions_arbu_by_dotrook-d4knv89.png' style='height: 160px;'></img> Image by: DotRook"
    link = "https://falloutequestria.fandom.com/wiki/Arbu"
    from = 0
[BucklinCross]
    name = "Buckling Cross"
    class = "settlement"
    lat = 3277
    lng = 3526
    zoom_level = 1
    description = "The base of the Manehattan Steel Rangers branch.<p><img src='https://static.wikia.nocookie.net/falloutequestria/images/a/ab/Bucklyn_cross_by_maeni.jpg' style='height: 160px;'></img></p> <p>Image by: maeni</p>"
    link = "https://falloutequestria.fandom.com/wiki/Bucklyn_Cross"
    from = 0
[Duskhoof]
    name = "Duskhoof"
    class = "settlement"
    lat = 3310
    lng = 3524
    zoom_level = 1
    description = "A small settlement of batponies."
    link = ""
    from = 3
[RaidersNest]
    name = "Raider's Nest"
    class = "settlement"
    lat = 3321
    lng = 3516
    zoom_level = 1
    description = "A nest of raiders vaguelly settlement shaped."
    link = ""
    from = 0
[Neighvarro]
    name = "Neighvarro"
    class = "settlement"
    lat = 3408
    lng = 3220
    zoom_level = 1
    description = "The Enclave's most millitarilly capable city and could've become its capital."
    link = "https://falloutequestria.fandom.com/wiki/Neighvarro"
    from = 0
[Stable1City]
    name = "Stable (1) City"
    class = "settlement"
    lat = 3414
    lng = 3275
    zoom_level = 1
    description = "A settlement of mainly pink cloud ghouls."
    link = "https://falloutequestria.fandom.com/wiki/Stable_City"
    from = 0
