[Cartwheel]
    name = "Cartwheel"
    class = "settlement"
    x = 3342
    y = 3177
    zoom_level = 1
    description = "A small trading town whose main establishment of note is the Equestrian Express courier service owned by Box Tape."
    link = ""
    from = 4
[HiddenValley]
    name = "Hidden Sands"
    class = "settlement steelranger"
    x = 3323
    y = 3181
    zoom_level = 1
    description = "The bunker where the New Pegasus Steel Rangers branch reside."
    link = ""
    from = 4
[TheBramble]
    name = "The Bramble"
    class = "settlement"
    x = 3307
    y = 3158
    zoom_level = 1
    description = "A bloodthirsty underground settlement with one of The Wasteland's deadliest gladiatorial arenas."
    link = ""
    from = 4
[NewPegasus]
    name = "New Pegasus"
    class = "post-war-capital rnp"
    x = 3284
    y = 3152
    zoom_level = 0
    description = "The bustling 'capital' on paper of the R.N.P. The only major pre-war equestrian city to avoid the bombs."
    link = ""
    from = 4
[NewPegasusStrip]
    name = "New Pegasus Strip"
    class = "settlement"
    x = 3274
    y = 3158
    zoom_level = 1
    description = "The wealthiest part of New Pegasus with its famous casinos."
    link = ""
    from = 4
[Freedom]
    name = "Freedom"
    class = "settlement"
    x = 3265
    y = 3159
    zoom_level = 1
    description = "The poor parts of New Pegasus, dominated by The Queens and the Van Damns."
    link = ""
    from = 4
[SpitfiresFlightAcademy]
    name = "Spitfire's Flight Academy"
    class = "settlement"
    x = 3266.5
    y = 3177.5
    zoom_level = 2
    description = "Homebase of The Anihhilators a group of former stable dwellers that don't take kindly to outsiders."
    link = ""
    from = 4
[Trotston]
    name = "Trotston"
    class = "settlement"
    x = 3269
    y = 3183
    zoom_level = 2
    description = "A technologically advanced and heavilly fortified settlement made by former stable dwellers from stable 9."
    link = ""
    from = 4
[FortSummit]
    name = "Fort Summit"
    class = "settlement unity"
    x = 3255
    y = 3180
    zoom_level = 2
    description = "A settlement created by an alicorn named Violet which is open to everyone fleeing persecution."
    link = ""
    from = 4
[CrimsonCanyon]
    name = "Crimson Canyon"
    class = "settlement talon"
    x = 3260
    y = 3185
    zoom_level = 1
    description = "The home of the Red Talon Company griffons one the best talon companies in The Wasteland."
    link = ""
    from = 4
[Appleton]
    name = "Appleton"
    class = "settlement enclave"
    x = 3244
    y = 3152
    zoom_level = 1
    description = "A large trading settlement that has a large Enclave presence due to it sitting underneath the cloud city of Stratus."
    link = ""
    from = 4
[Stratus]
    name = "Stratus"
    class = "settlement enclave"
    x = 3246
    y = 3147
    zoom_level = 1
    description = "One of the Enclave's smaller cities, famous for its everlasting alliance with Nimbus."
    link = ""
    from = 4
[Stable28]
    name = "Stable 28"
    class = "settlement stable"
    x = 3357
    y = 3163
    zoom_level = 1
    description = "Shadow Star's still active stable. An earth pony stable thats recently closed off from the outside."
    link = ""
    from = 4
[TheKingdom]
    name = "The Kingdom"
    class = "settlement"
    x = 3394
    y = 3075
    zoom_level = 1
    description = "A grand settlement open to everyone so long as they don't hold any prejudices or are violent, lead by Empress Sheena and Emperor Periwinkle Punch."
    link = ""
    from = 4
[LittleHoof]
    name = "Little Hoof"
    class = "settlement"
    x = 3322
    y = 3167
    zoom_level = 2
    description = "A settlement composed entirelly of fillies and colts, hidden from the outside."
    link = ""
    from = 4
[MillCityTower]
    name = "Mill City Tower"
    class = "settlement enclave"
    x = 3387
    y = 2973
    zoom_level = 1
    description = "A large spire located in the centre of Whinneapolis, its used as a major centre of Enclave research."
    link = ""
    from = 4
[Sorchville]
    name = "Scorchville"
    class = "settlement"
    x = 3405
    y = 3042
    zoom_level = 2
    description = "A small settlement near the pre-war city of Lakewood with a peculiar cult of a robot by the name of Serendipidy."
    link = ""
    from = 4
[Branch]
    name = "Branch"
    class = "settlement"
    x = 3415
    y = 3030
    zoom_level = 2
    description = "A medium settlement in Saint's Parish famous for its exploding grain silos."
    link = ""
    from = 4
[Pins]
    name = "Pins"
    class = "settlement"
    x = 3335
    y = 3152
    zoom_level = 2
    description = "A small settlement of slavers."
    link = ""
    from = 4
[CrossroadsTradingPosts]
    name = "Crossroads Trading Posts"
    class = "settlement rnp"
    x = 3260.542578125
    y = 3170.671875
    zoom_level = 2
    description = "A large trading settlement built on an overpass and controlled by the R.N.P."
    link = ""
    from = 4
[Coven]
    name = "Coven"
    class = "settlement"
    x = 3257.3125 
    y = 3169.1875
    zoom_level = 2
    description = "A small trading settlement with a large zebra population."
    link = ""
    from = 4
