[Stable9]
    name = "Stable 9"
    class = "misc-poi stable"
    x = 3307
    y = 3182
    zoom_level = 2
    description = "An old abandoned and sealed from the outside stable, a lot of bloodwings seem to live there."
    link = ""
    from = 4
[Stable14]
    name = "Stable 14"
    class = "misc-poi stable"
    x = 3283
    y = 3183
    zoom_level = 2
    description = "An empty griffon stable now used as base by the Triggerponies."
    link = ""
    from = 4
[HaloOnePowerStation]
    name = "Halo One Power Station"
    class = "misc-poi rnp"
    x = 3295
    y = 3192
    zoom_level = 2
    description = "A large solar updraft and underground hydroelectric power plant that is constantly being fought over by the R.N.P, Steel Rangers and Enclave."
    link = ""
    from = 4
[JetblueSkyport]
    name = "Jetblue Skyport"
    class = "misc-poi rnp"
    x = 3303
    y = 3173
    zoom_level = 2
    description = "The old international airport of Los Pegasos, now used as a R.N.P. base."
    link = ""
    from = 4
[NewPegasusDam]
    name = "New Pegasus Dam"
    class = "misc-poi rnp"
    x = 3330
    y = 3165
    zoom_level = 1
    description = "A very large hydroelectric power plant thats under the control of the R.N.P. with constant attack by the New Legion."
    link = ""
    from = 4
[FnFTools]
    name = "F&F Tools"
    class = "misc-poi"
    x = 3316
    y = 3173
    zoom_level = 2
    description = "The old F&F factory."
    link = ""
    from = 4
[GreenMistValley]
    name = "Green Mist Valley"
    class = "misc-poi radiation"
    x = 3352
    y = 3166
    zoom_level = 1
    description = "A vallley of radioactive myst filled with feral ghouls."
    link = ""
    from = 4
[EAMSStation1]
    name = "E.A.M.S. Station 1"
    class = "intra-settlement eams"
    x = 3297
    y = 3157
    zoom_level = 2
    description = ""
    link = ""
    from = 2
[QueensSchoolOfInterpretation]
    name = "Queen's School of Interpretation"
    class = "intra-settlement"
    x = 3262
    y = 3157
    zoom_level = 3
    description = "The H.Q. of The Queens, a former school of theatre."
    link = ""
    from = 4
[VanDamns]
    name = "Van Damns'"
    class = "intra-settlement weapons"
    x = 3268
    y = 3162
    zoom_level = 3
    description = "A shady magical energy weapons story."
    link = ""
    from = 4
[LuckyHorseshoe]
    name = "The Lucky Horseshoe"
    class = "intra-settlement casino"
    x = 3273
    y = 3157
    zoom_level = 3
    description = "The tallest building in New Pegasus and home of Mr. Tops, New Pegasus' mysterious controller. It used to be a bustling casino but now very few get to enter it."
    link = ""
    from = 4
[DemocracysPalace]
    name = "Democracy's Palace"
    class = "intra-settlement rnp"
    x = 3276
    y = 3149
    zoom_level = 3
    description = "The presidential palace of the R.N.P. built over a massive luxury resort."
    link = ""
    from = 2
[MatchnTariffs]
    name = "Match and Tariff's"
    class = "intra-settlement shop"
    x = 3266
    y = 3157
    zoom_level = 3
    description = "A general store owned by a stallion couple."
    link = ""
    from = 4
[EmperorsPalace]
    name = "Emperor's Palace"
    class = "intra-settlement casino"
    x = 3272
    y = 3158
    zoom_level = 3
    description = "A large luxury casino built like a roaman building."
    link = ""
    from = 4
[TheGrandRoyale]
    name = "The Grand Royale"
    class = "intra-settlement casino"
    x = 3271
    y = 3157
    zoom_level = 3
    description = "A V shaped casino with the creepiest of staff, all masked. Its meant to be a luxury semi-resort with a pool."
    link = ""
    from = 4
[TheApplewoodResortnCasino]
    name = "The Applewood Resort & Casino"
    class = "intra-settlement casino"
    x = 3270
    y = 3158
    zoom_level = 3
    description = "A tacky casino filled to the brim with posters and imagery of pre-war celebrities."
    link = ""
    from = 4
[Stable20Hotel]
    name = "Stable 20 Hotel"
    class = "intra-settlement stable"
    x = 3271.5
    y = 3154
    zoom_level = 3
    description = "A hotel built on what was New Pegasus' main stable."
    link = ""
    from = 4
[HonestHeartsDetectiveAgency]
    name = "Honest Hearts Detective Agency"
    class = "intra-settlement"
    x = 3269
    y = 3153
    zoom_level = 3
    description = "A detective agency owned by a synth pony named Honest Hearts."
    link = ""
    from = 4
[Stable97]
    name = "Stable 97"
    class = "misc-poi stable"
    x = 3394
    y = 2976
    zoom_level = 2
    description = "A reactivated stable by the Enclave for their 'Devil's Child' programme."
    link = ""
    from = 4
[TwinCitiesDam]
    name = "Twin Cities Dam"
    class = "misc-poi enclave"
    x = 3391
    y = 3000
    zoom_level = 1
    description = "A large dam that powers both Saint's Parish and Whinneapolis."
    link = ""
    from = 4
[LittlehornValley]
    name = "Littlehorn Valley"
    class = "misc-poi"
    x = 3256
    y = 2856
    zoom_level = 1
    description = "A valley famous for a massacre that took place at the early days of The Great War."
    link = ""
    from = 0
[LunasSchoolForGiftedUnicorns]
    name = "Luna's School For Gifted Unicorns"
    class = "misc-poi"
    x = 3250
    y = 2856
    zoom_level = 2
    description = "A magic school for unicorns ran by Princess Luna, it was the site of a massacre."
    link = ""
    from = 0
[KingdomsMansion]
    name = "Kingdom's Mansion"
    class = "intra-settlement lodge"
    x = 3395
    y = 3074
    zoom_level = 2
    description = "The house of Empress Sheena and Emperor Punch, features a very extensive medical complex."
    link = ""
    from = 4
[AbsentRuins]
    name = "Absent Ruins"
    class = "misc-poi"
    x = 3392
    y = 3073
    zoom_level = 2
    description = "Ruins of the old pre-war city of Reinchester, now said to be haunted."
    link = ""
    from = 4
[MASEBS10]
    name = "M.A.S.E.B.S. Tower 10"
    class = "misc-poi"
    x = 3345
    y = 3175
    zoom_level = 2
    description = ""
    link = ""
    from = 4
[FirstBoulevard]
    name = "First Boulevard"
    class = "intra-settlement"
    x = 3380
    y = 2991
    zoom_level = 2
    description = "The wealthiest part of Whinnieapolis"
    link = ""
    from = 4
[KingdomsMedicalWing]
    name = "Kingdom's Medical Wing"
    class = "intra-settlement medical"
    x = 3395.21875
    y = 3073.40625
    zoom_level = 3
    description = "One of the largest collections off medical staff in the wasteland."
    link = ""
    from = 4
[SilverSnipsArmoury]
    name = "Silver Snip's Armoury"
    class = "intra-settlement armour"
    x = 3341.734375
    y = 3177.296875
    zoom_level = 3
    description = "A small tailor shop owned by an unicorn mare named Silver Snip."
    link = ""
    from = 4
[PurpleHeartClinic]
    name = "Purple Heart Clinic"
    class = "intra-settlement medical"
    x = 3342.640625
    y = 3177.0703125
    zoom_level = 3
    description = "A small clinic owned by an unicorn stallion named Purple Heart."
    link = ""
    from = 4
[DriftsPlace]
    name = "Drift's Place"
    class = "intra-settlement shop"
    x = 3342.25
    y = 3176.90625
    zoom_level = 3
    description = "A small shop owned by a ghoul stallion named Drift Fast."
    link = ""
    from = 4
[MommasGuns]
    name = "Momma's guns"
    class = "intra-settlement weapons"
    x = 3342.40625
    y = 3176.8125
    zoom_level = 3
    description = "A small weapons store owned by a mare named Redheart."
    link = ""
    from = 4
[EquestrianExpress]
    name = "Equestrian Express"
    class = "intra-settlement"
    x = 3341.390625
    y = 3177.390625
    zoom_level = 3
    description = "The main place for the Equestrian Express courier service owned by an old earth pony stallion named Box Tape."
    link = ""
    from = 4
[GrimsShack]
    name = "Grim's Shack"
    class = "intra-settlement"
    x = 3270.1875
    y = 3183.5
    zoom_level = 3
    description = "An old run down shack that used to be a repair shop owned by a unicorn nammed Grimoire Spell."
    link = ""
    from = 4
[EnclaveSkyport]
    name = "Enclave Skyport"
    class = "intra-settlement enclave"
    x = 3275.09375
    y = 3156.78125
    zoom_level = 3
    description = "The last functional cloud elevator in New Pegasus, turned basically the official embassy of the Enclave in the city, rarely gets any activity and as such Kittersfly(The pegasus stallion responsible for it) also runs two side businesses in the form of a robot repair shop and a clinic."
    link = ""
    from = 4
[Stable34]
    name = "Stable 34"
    class = "misc-poi stable"
    x = 3268.25
    y = 3184.15625
    zoom_level = 2
    description = "The old stable where The Anihilators are from, now owned by Trotston which has sparked a fierce rivalry between the two."
    link = ""
    from = 4
