[Chapel]
    name = "Chapel"
    class = "settlement"
    x = 3450.263671875
    y = 3705.296875
    zoom_level = 2
    description = "Home of the <a href='https://falloutequestria.fandom.com/wiki/Crusaders_(Project_Horizons)'>Crusaders.</a><p><img src='https://static.wikia.nocookie.net/falloutequestria/images/2/22/Hoofington_Crusaders.png' style='height: 160px;'></img></p> <p>Image by: DotRook</p>"
    link = ""
    from = 5
[Flotsam]
    name = "Flotsam"
    class = "settlement"
    x = 3441
    y = 3709
    zoom_level = 2
    description = "A small settlement built over a floating platform."
    link = ""
    from = 5
[Megamart]
    name = "Megamart"
    class = "settlement"
    x = 3439
    y = 3698
    zoom_level = 1
    description = "<a href='https://falloutequestria.fandom.com/wiki/Bottlecap_(Project_Horizons)'>Bottlecap</a>'s settlement, built on trade of goods."
    link = ""
    from = 5
[Paradise]
    name = "Paradise"
    class = "settlement redeye"
    x = 3451.015625
    y = 3722.8125
    zoom_level = 1
    description = "<a href='https://falloutequestria.fandom.com/wiki/Usury_(Project_Horizons)'>Usury</a>'s settlement, built on slave trade."
    link = ""
    from = 5
[Flank]
    name = "Flank(Stable 69)"
    class = "settlement stable"
    x = 3461
    y = 3691
    zoom_level = 1
    description = "<a href='https://falloutequestria.fandom.com/wiki/Caprice_(Project_Horizons)'>Caprice</a>'s settlement, built on prostitution."
    link = ""
    from = 5
[Boardwalk]
    name = "Boardwalk"
    class = "settlement"
    x = 3430
    y = 3695
    zoom_level = 2
    description = "A small settlement built on old docks."
    link = ""
    from = 5
[Riverside]
    name = "Riverside"
    class = "settlement"
    x = 3443
    y = 3707
    zoom_level = 2
    description = "A small hellhound/diamond dog settlement."
    link = ""
    from = 5
[Thunderhead]
    name = "Thunderhead"
    class = "settlement enclave"
    x = 3448
    y = 3711
    zoom_level = 1
    description = "A city to rival Neighvarro, Thunderhead is one of the Enclave's most powerfull cities and the most technologically advanced. <a href='https://falloutequestria.fandom.com/wiki/Morning_Glory_(Project_Horizons)'>Morning Glory</a>'s home.<img src='https://static.wikia.nocookie.net/falloutequestria/images/3/39/Grand_Pegasus_Enclave.png' style='height: 160px;'></img> Image by: DotRook"
    link = "https://falloutequestria.fandom.com/wiki/Thunderhead_(Project_Horizons)"
    from = 5
[HoofingtonSportsArena]
    name = "Hoofington Sports Arena"
    class = "settlement"
    x = 3440.078125
    y = 3701.845703125
    zoom_level = 2
    description = "The H.Q. of the <a href='https://falloutequestria.fandom.com/wiki/Reapers_(Project_Horizons)'>Reapers</a>. <p><img src='https://static.wikia.nocookie.net/falloutequestria/images/6/66/Reapersfactiondotrook.png' style='height: 160px;'></img></p> <p>Image by: DotRook</p>"
    link = ""
    from = 5
[IronmareNavalStation]
    name = "Ironmare Naval Station"
    class = "settlement steelranger"
    x = 3436
    y = 3716
    zoom_level = 2
    description = "The base of operations for the Hoofington Steel Rangers branch.<img src='https://static.wikia.nocookie.net/falloutequestria/images/8/84/Steelrangersfactiondotrook.png' style='height: 160px;'></img> Image by: DotRook"
    link = ""
    from = 5
[HoofingtonUniversity]
    name = "Hoofington University"
    class = "settlement"
    x = 3458.1640625
    y = 3712.755859375
    zoom_level = 1
    description = "The old university of Hoofington now the home base of the <a href='https://falloutequestria.fandom.com/wiki/Collegiate_(Project_Horizons)'>The Collegiate</a>.<p><img src='https://static.wikia.nocookie.net/falloutequestria/images/6/6a/Collegiatefactiondotrook.png' style='height: 160px;'></img></p> <p>Image by: DotRook</p>"
    link = "https://falloutequestria.fandom.com/wiki/University_(Project_Horizons)"
    from = 5
[Stable152]
    name = "Stable 152"
    class = "settlement stable"
    x = 3455
    y = 3690
    zoom_level = 2
    description = "An active sealed millitary stable, one of the largest stables."
    link = ""
    from = 2
[BrimstonesFall]
    name = "Brimstone's Fall"
    class = "settlement redeye"
    x = 3457
    y = 3695
    zoom_level = 2
    description = "A medium slaver settlement."
    link = ""
    from = 5
[Stockyard]
    name = "Stockyard"
    class = "settlement"
    x = 3449
    y = 3689
    zoom_level = 2
    description = "A small settlement built over a trash pit."
    link = ""
    from = 5
[Meatlocker]
    name = "Meatlocker"
    class = "settlement"
    x = 3446.953125
    y = 3721.662109375
    zoom_level = 2
    description = "A ghoul settlement built on the old Hoofington General/Memorial Hospital."
    link = ""
    from = 5
[NightmareCastle]
    name = "Nightmare Castle"
    class = "settlement"
    x = 3454.9375
    y = 3726.5625
    zoom_level = 2
    description = "Princess Luna's ancient castle, now used as a sort of stable by the descendants of the night guard. Very inbred."
    link = ""
    from = 5
[ElysiumResort]
    name = "Elysium Resort"
    class = "settlement"
    x = 3468.984375 
    y = 3694.7578125
    zoom_level = 1
    description = "The luxury resort turned serf plantation settlement, owned by <a href='https://falloutequestria.fandom.com/wiki/Society_(Project_Horizons)'>The Society</a>.<img src='https://static.wikia.nocookie.net/falloutequestria/images/5/5a/Societyfactiondotrook.png' style='height: 160px;'></img> Image by: DotRook"
    link = ""
    from = 5
[Highlands]
    name = "The Highlands"
    class = "settlement"
    x = 3463
    y = 3724
    zoom_level = 2
    description = "The home of the odd earth ponies known as the Highlanders whose existence extends far before The Great War, they are fiercly independent."
    link = "https://falloutequestria.fandom.com/wiki/Highlanders_(Project_Horizons)"
    from = 5
[FillydelphiaFunFarm]
    name = "Fillidelphia Fun Farm"
    class = "settlement redeye"
    x = 3372
    y = 3546
    zoom_level = 1
    description = "A large slaver settlement controlled by <a href='https://falloutequestria.fandom.com/wiki/Red_Eye'>Red Eye.</a>"
    link = "https://falloutequestria.fandom.com/wiki/Fillydelphia_FunFarm"
    from = 0
[MiramareAirStation]
    name = "Miramare Air Station"
    class = "settlement enclave"
    x = 3458.5
    y = 3691
    zoom_level = 3
    description = "A wartime millitary airbase, famously used by <a href='https://falloutequestria.fandom.com/wiki/Macintosh%27s_Marauders_(Project_Horizons)'>Macintosh's Marauders</a> now owned by the Enclave."
    link = ""
    from = 5
[RainbowDashSkyport]
    name = "Rainbow Dash Skyport"
    class = "settlement enclave"
    x = 3452.7734375
    y = 3716.986328125
    zoom_level = 2
    description = "The old international skyport of Hoofington, now the Enclave's largest base in the region."
    link = ""
    from = 5
[Stable99]
    name = "Stable 99"
    class = "settlement stable"
    x = 3434.04296875
    y = 3694.5908203125
    zoom_level = 2
    description = "<a href='https://falloutequestria.fandom.com/wiki/Blackjack_(Project_Horizons)'>Blackjack</a>'s and <a href='https://falloutequestria.fandom.com/wiki/P-21_(Project_Horizons)'>P-21</a>'s stable. One of Stable-Tec's largest."
    link = "https://falloutequestria.fandom.com/wiki/Stable_99_(Project_Horizons)"
    from = 5
[Toll]
    name = "Toll"
    class = "settlement"
    x = 3437
    y = 3709
    zoom_level = 3
    description = "A small settlement on a bridge."
    link = ""
    from = 5
[FlashIndustries]
    name = "Flash Industries"
    class = "settlement"
    x = 3441.9921875
    y = 3717.09765625
    zoom_level = 2
    description = "An old factory and the home base of the Flash Fillies. The factory manufactured energy weapons and other laser based implements, its responsible for most laser-based weapons found in Equestria today. The Flash Fillies are also fierce rivals of the Burner Boys."
    link = ""
    from = 5
[RocketTown]
    name = "Rocket Town"
    class = "settlement radiation"
    x = 3461.09375
    y = 3718.65625 
    zoom_level = 2
    description = "A ghoul settlement of mainly the former workers of the Luna Space Centre."
    link = ""
    from = 5
[Scrapyard]
    name = "Scrapyard"
    class = "settlement"
    x = 3453.4765625
    y = 3717.580078125
    zoom_level = 3
    description = "A small village settlement on a junkyard, most of the buildings were made of overturned skywagons. Famous for... selling scrap to the Enclave."
    link = ""
    from = 5
[HalfheartsHQ]
    name = "Halfhearts H.Q."
    class = "settlement"
    x = 3455.9375
    y = 3701.95703125
    zoom_level = 1
    description = "The headquarters of the Halfhearts gang, a very powerful gang that controls most of the western side of the Hoofington River."
    link = ""
    from = 5
[BurnerBoysHQ]
    name = "Burner Boys H.Q."
    class = "settlement"
    x = 3439.53125
    y = 3726.375
    zoom_level = 2
    description = "The headquarters of the Burner Boys gang. A gang of sick ponies who tend to do horrible things to families. Fierce rivals of the Flash Fillies"
    link = ""
    from = 5
