[PonaRosa]
    name = "Pona Rosa"
    class = "settlement"
    lat = 3569
    lng = 3616
    zoom_level = 1
[NewCloudsdale]
    name = "New Cloudsdale"
    class = "post-war-capital"
    lat = 3548
    lng = 3395
    zoom_level = 0
[Portharbour]
    name = "Portharbour"
    class = "settlement"
    lat = 3785
    lng = 3474
    zoom_level = 1
[Stable11]
    name = "Stable 11"
    class = "settlement"
    lat = 3593
    lng = 3533
    zoom_level = 2
