[PonaRosa]
    name = "Pona Rosa"
    class = "settlement"
    x = 3569
    y = 3607
    zoom_level = 1
    description = "A bustling trade settlement that is meant to be a neutral zone for all gangs in the regions built within an old shopping mall. Its ran by an earth pony mare named Roulette, the only pre-day-of-sunshine-and-rainbows settlement from Dead End."
    link = ""
    from = 9
[NewCloudsdale]
    name = "New Cloudsdale"
    class = "post-war-capital enclave"
    x = 3548
    y = 3395
    zoom_level = 0
    description = "The 'official' capital of the Grand Pegasus Enclave and its largest city, its size is comparable to a pre-war metropolis."
    link = ""
    from = 2
[Portharbour]
    name = "Portharbour"
    class = "settlement"
    x = 3785
    y = 3474
    zoom_level = 1
    description = "'Is it a port or a harbour?!'"
    link = ""
    from = 2
[Stable11]
    name = "Stable 11"
    class = "settlement stable"
    x = 3593
    y = 3533
    zoom_level = 1
    description = "Cherry Fizz's still active stable that also regularly trades with the outside. It's overmare has recently been 'murdered'."
    link = ""
    from = 10
[Stable9]
    name = "Stable 9"
    class = "settlement stable"
    x = 3758
    y = 3497
    zoom_level = 1
    description = "A still active and friendly stable that constantly trades with the outside."
    link = ""
    from = 6
[HoofRiver]
    name = "Hoof River"
    class = "settlement"
    x = 3681
    y = 3508
    zoom_level = 1
    description = "A small town turned small trading settlement."
    link = ""
    from = 6
[Parkdale]
    name = "Parkdale"
    class = "settlement"
    x = 3727
    y = 3507
    zoom_level = 1
    description = "A small village famous for its cemitery of travellers."
    link = ""
    from = 6
[Stormgate]
    name = "Stormgate"
    class = "settlement"
    x = 3791
    y = 3466
    zoom_level = 1
    description = "A small port settlement."
    link = ""
    from = 6
[Ticklemoose]
    name = "Ticklemoose"
    class = "settlement"
    x = 3817
    y = 3438
    zoom_level = 1
    description = "A medium coastal settlement. Known for its cheese and... odd name."
    link = ""
    from = 6
[Maredras]
    name = "Maredras"
    class = "settlement"
    x = 3663
    y = 3500
    zoom_level = 1
    description = "An old town with a weird billboard."
    link = ""
    from = 6
[Fold]
    name = "Fold"
    class = "settlement"
    x = 3671
    y = 3522
    zoom_level = 1
    description = "A lumber settlement owned by the Timberjacks."
    link = ""
    from = 6
[ThreeRivers]
    name = "Three Rivers"
    class = "settlement"
    x = 3552
    y = 3443
    zoom_level = 1
    description = "A small settlement surrounded by 3 nascent tributaries."
    link = ""
    from = 6
