[NeuePurlin]
    name = "Neue-Purlin"
    class ="pre-war-capital"
    x = 3417
    y = 3790
    zoom_level = 0
    description = ""
    link = ""
    from = 2
[Trabisberg]
    name = "Trabisberg"
    class ="city"
    x = 3408
    y = 3741
    zoom_level = 1
    description = ""
    link = ""
    from = 2
[Hufburg]
    name = "Hufburg"
    class = "city"
    x = 3482
    y = 3778
    zoom_level = 1
    description = ""
    link = ""
    from = 2