[PortoCapital]
    name = "Porto Capital"
    class ="pre-war-capital"
    x = 2202
    y = 2919
    zoom_level = 0
    description = "The capital of the Federal Republic of Ausil."
    link = ""
    from = 2
[PortoNovo]
    name = "Porto Novo"
    class ="city"
    x = 2240
    y = 2869
    zoom_level = 1
    description = ""
    link = ""
    from = 2
[FortalezaDoCouro]
    name = "Fortaleza do Couro"
    class ="city"
    x = 2262
    y = 2822
    zoom_level = 1
    description = ""
    link = ""
    from = 2
[JoaoPonei]
    name = "João Ponei"
    class ="city"
    x = 2146
    y = 3010
    zoom_level = 1
    description = ""
    link = ""
    from = 2
[Cascoiba]
    name = "Cascoibá"
    class ="city"
    x = 2013
    y = 3159
    zoom_level = 1
    description = ""
    link = ""
    from = 2
[BelasPraias]
    name = "Belas Praias"
    class ="city"
    x = 1983
    y = 3144
    zoom_level = 1
    description = ""
    link = ""
    from = 2
[CrinaDeJaneiro]
    name = "Crina de Janeiro"
    class ="city"
    x = 1972
    y = 2965
    zoom_level = 1
    description = ""
    link = ""
    from = 2
[Nitrotaroi]
    name = "Nitrotarói"
    class ="city"
    x = 1894
    y = 3090
    zoom_level = 1
    description = ""
    link = ""
    from = 2
[BeloMirante]
    name = "Belo Mirante"
    class ="city"
    x = 1807
    y = 3046
    zoom_level = 1
    description = ""
    link = ""
    from = 2
[SaoPasto]
    name = "São Pasto"
    class ="city"
    x = 1810
    y = 2917
    zoom_level = 1
    description = ""
    link = ""
    from = 2
[Relinchem]
    name = "Relinchém"
    class ="city"
    x = 1781
    y = 2748
    zoom_level = 1
    description = ""
    link = ""
    from = 2
[Morcegueira]
    name = "Morcegueira"
    class ="city"
    x = 1770
    y = 3178
    zoom_level = 1
    description = ""
    link = ""
    from = 2
[Pontaus]
    name = "Pontaus"
    class ="city"
    x = 1621
    y = 3019
    zoom_level = 1
    description = ""
    link = ""
    from = 2
[NoOeste]
    name = "Nó Oeste"
    class ="city"
    x = 1586
    y = 2699
    zoom_level = 1
    description = ""
    link = ""
    from = 2
