[CrystalCity]
    name = "Crystal City"
    class ="pre-war-capital"
    x = 4173
    y = 3579
    zoom_level = 0
    description = ""
    link = ""
    from = 1
[Ceffyldd]
    name = "Ceffyldd"
    class = "city"
    x = 4179
    y = 3683
    zoom_level = 1
    description = ""
    link = ""
    from = 2
[Birneigham]
    name = "Birneigham"
    class = "city"
    x = 4139
    y = 3588
    zoom_level = 1
    description = ""
    link = ""
    from = 2
[Leads]
    name = "Leads"
    class = "city"
    x = 4085
    y = 3449
    zoom_level = 1
    description = ""
    link = ""
    from = 2
[YCastell]
    name = "Y Castell"
    class = "city"
    x = 4124
    y = 3736
    zoom_level = 1
    description = ""
    link = ""
    from = 2
[Edinhoof]
    name = "Edinhoof"
    class = "city"
    x = 3919
    y = 3059
    zoom_level = 1
    description = ""
    link = ""
    from = 2
[Oliverland]
    name = "Oliverland"
    class = "city"
    x = 4412
    y = 2986
    zoom_level = 1
    description = ""
    link = ""
    from = 2
[Briddlefast]
    name = "Briddlefast"
    class = "city"
    x = 4145
    y = 3924
    zoom_level = 1
    description = ""
    link = ""
    from = 2
[Cruscllin]
    name = "Crusclin"
    class = "city"
    x = 4109
    y = 3931
    zoom_level = 1
    description = ""
    link = ""
    from = 2
[Lerpick]
    name = "Lerpick"
    class = "city"
    x = 4285
    y = 4296
    zoom_level = 1
    description = ""
    link = ""
    from = 2
