[Ponyville]
    name = "Ponyville" #Name
    class = "city" #Icon, font colour and other CSS stuff
    x = 3263 #X
    y = 3295 #Y
    zoom_level = 1 #The zoom level for when this PoI will appear, goes from 0(Always on) to 3(Inside a city)
    description = "A small unnassuming village that was the home of the Mane 6 aka. the Ministry Mares." #The description of the poi, fully html compliant
    link = "" #A link to say a wiki page of this poi
    from = 1 #where this poi is from
[Canterlot]
    name = "Canterlot"
    class ="pre-war-capital"
    x = 3421
    y = 3274
    zoom_level = 0
    description = "The old city on a hill and former capital of Equestria."
    link = ""
    from = 1
[Baltimare]
    name = "Baltimare"
    class = "city"
    x = 3330
    y = 3432
    zoom_level = 1
    description = ""
    link = ""
    from = 1
[Cloudsdale]
    name = "Cloudsdale"
    class = "city"
    x = 3328
    y = 3271
    zoom_level = 1
    description = ""
    link = ""
    from = 1
[NeighOrleans]
    name = "Neigh Orleans"
    class = "city"
    x = 3168
    y = 3267
    zoom_level = 1
    description = ""
    link = ""
    from = 1
[LosAlicorn]
    name = "Los Alicorn"
    class = "city"
    x = 3230
    y = 3212
    zoom_level = 1
    description = ""
    link = ""
    from = 4
[Appleloosa]
    name = "Appleloosa"
    class = "city"
    x = 3264
    y = 3236
    zoom_level = 1
    description = ""
    link = ""
    from = 1
[LosPegasos]
    name = "Los Pegasos"
    class = "city"
    x = 3286
    y = 3163
    zoom_level = 1
    description = "Known formerly as the city of vice, it used to be a major cloud and ground metropolis."
    link = ""
    from = 1
[Detrot]
    name = "Detrot"
    class = "city"
    x = 3198
    y = 3038
    zoom_level = 1
    description = ""
    link = ""
    from = 2
[Whinnieapolis]
    name = "Whinnieapolis"
    class = "city"
    x = 3385
    y = 2982
    zoom_level = 1
    description = ""
    link = ""
    from = 4
[SaintsParish]
    name = "Saint's Parish"
    class = "city"
    x = 3404
    y = 3017
    zoom_level = 1
    description = ""
    link = ""
    from = 4
[Reinchester]
    name = "Reinchester"
    class = "city"
    x = 3401
    y = 3079
    zoom_level = 1
    description = ""
    link = ""
    from = 4
[Vanhoover]
    name = "Vanhoover"
    class = "city"
    x = 3705
    y = 3465
    zoom_level = 1
    description = ""
    link = ""
    from = 6
[Zebratown]
    name = "Zebratown"
    class = "city"
    x = 3391
    y = 3266
    zoom_level = 1
    description = ""
    link = ""
    from = 0
[SplendidFalls]
    name = "Splendid Falls"
    class = "city"
    x = 3434
    y = 3368
    zoom_level = 1
    description = "A former tiny village only known for its waterfalls turned open settlement."
    link = ""
    from = 2
[Manehattan]
    name = "Manehattan"
    class = "city"
    x = 3316
    y = 3500
    zoom_level = 1
    description = ""
    link = ""
    from = 1
[Fillydelphia]
    name = "Fillydeplhia"
    class = "city"
    x = 3376
    y = 3555
    zoom_level = 1
    description = ""
    link = ""
    from = 1
[Hoofington]
    name = "Hoofington"
    class = "city"
    x = 3451
    y = 3710
    zoom_level = 1
    description = ""
    link = ""
    from = 5
[Foaledo]
    name = "Foaledo"
    class = "city"
    x = 3608
    y = 3519
    zoom_level = 1
    description = ""
    link = ""
    from = 2
[Maretropolis]
    name = "Maretropolis"
    class = "city"
    x = 3457
    y = 2857
    zoom_level = 1
    description = ""
    link = ""
    from = 2
[Portlandia]
    name = "Portlandia"
    class = "city"
    x = 3782
    y = 3475
    zoom_level = 1
    description = ""
    link = ""
    from = 6
[Seaddle]
    name = "Seaddle"
    class = "city"
    x = 3865
    y = 3495
    zoom_level = 1
    description = ""
    link = ""
    from = 6
[Lakewood]
    name = "Lakewood"
    class = "city"
    x = 3412
    y = 3047
    zoom_level = 1
    description = ""
    link = ""
    from = 4
[GravelCity]
    name = "Gravel City"
    class = "city"
    x = 3409
    y = 3129
    zoom_level = 1
    description = "A small gem mining town, now mostly empty save it for the cave which houses a settlement of hellhounds and ponies."
    link = ""
    from = 4