[Starynopla]
    name = "Starynopla"
    class ="pre-war-capital"
    x = 2931
    y = 2974
    zoom_level = 0
    description = "The fully planned and highly automated former capital of the Queendom of Ezpassiôn. Now covered by the deadly Fog."
    link = ""
    from = 2
[Liscasco]
    name = "Liscasco"
    class = "city"
    x = 2888
    y = 2960
    zoom_level = 1
    description = ""
    link = ""
    from = 2
[Sulporta]
    name = "Sulporta"
    class = "city"
    x = 2918
    y = 3008
    zoom_level = 1
    description = ""
    link = ""
    from = 2
[Cascorto]
    name = "Cascôrto"
    class = "city"
    x = 2883
    y = 3011
    zoom_level = 1
    description = ""
    link = ""
    from = 2
[Popaporto]
    name = "Popaporto"
    class = "city"
    x = 2891
    y = 3027
    zoom_level = 1
    description = ""
    link = ""
    from = 2
[Portroto]
    name = "Portrôto"
    class = "city"
    x = 2953
    y = 3043
    zoom_level = 1
    description = ""
    link = ""
    from = 2
[Estibordoburgo]
    name = "Estibordoburgo"
    class = "city"
    x = 3002
    y = 3012
    zoom_level = 1
    description = ""
    link = ""
    from = 2
[Boencia]
    name = "Boençia"
    class = "city"
    x = 3030
    y = 2927
    zoom_level = 1
    description = ""
    link = ""
    from = 2
[SunkenSunAnkh]
    name = "Sunkén Sun Ankh"
    class = "city"
    x = 2990
    y = 2952
    zoom_level = 1
    description = "The former largest kirin city outside of the qilin lands."
    link = ""
    from = 2
[Thalesia]
    name = "Thalesia"
    class = "city"
    x = 2968
    y = 2901
    zoom_level = 1
    description = "The world's largest city, so large it was beyond certain small countries, at its peak Thalesia had 1.5 Billion inhabitants."
    link = ""
    from = 2
[Norteporta]
    name = "Norteporta"
    class = "city"
    x = 2966
    y = 2969
    zoom_level = 1
    description = ""
    link = ""
    from = 2
[Cruzada]
    name = "Cruzada"
    class = "city"
    x = 2926
    y = 2935
    zoom_level = 1
    description = ""
    link = ""
    from = 2
[RioLeste]
    name = "Rio Leste"
    class = "city"
    x = 2967
    y = 2811
    zoom_level = 1
    description = ""
    link = ""
    from = 2
[TerraNova]
    name = "Terra Nova"
    class = "city"
    x = 2933 
    y = 2821
    zoom_level = 1
    description = ""
    link = ""
    from = 2
[Remota]
    name = "Remota"
    class = "city"
    x = 3010
    y = 3022
    zoom_level = 1
    description = ""
    link = ""
    from = 2
