[Botrota]
    name = "Botrotá"
    class ="pre-war-capital"
    x = 1810
    y = 2098
    zoom_level = 0
    description = ""
    link = ""
    from = 2
[Mararrabo]
    name = "Mararrabo"
    class ="city"
    x = 1877
    y = 2302
    zoom_level = 1
    description = ""
    link = ""
    from = 2