[Griffiedra]
    name = "Griffiedra (Griffonstone)"
    class ="pre-war-capital"
    x = 3208
    y = 4415
    zoom_level = 0
    description = ""
    link = ""
    from = 1
[Garrid]
    name = "Garrid"
    class = "city"
    x = 3186
    y = 4494
    zoom_level = 1
    description = ""
    link = ""
    from = 2
[Zarapluma]
    name = "Zarapluma"
    class = "city"
    x = 3014
    y = 4343
    zoom_level = 1
    description = ""
    link = ""
    from = 2
[LasPatas]
    name = "Las Patas"
    class = "city"
    x = 3121
    y = 4256
    zoom_level = 1
    description = ""
    link = ""
    from = 2
[Patarlona]
    name = "Patarlona"
    class = "city"
    x = 3196
    y = 4150
    zoom_level = 1
    description = ""
    link = ""
    from = 2
[Sevala]
    name = "Sevala"
    class = "city"
    x = 3209
    y = 4071
    zoom_level = 1
    description = ""
    link = ""
    from = 2
[Grifencia]
    name = "Griféncia"
    class = "city"
    x = 3284
    y = 4075
    zoom_level = 1
    description = ""
    link = ""
    from = 2
[Picao]
    name = "Picao"
    class = "city"
    x = 3278
    y = 4280
    zoom_level = 1
    description = ""
    link = ""
    from = 2
[VitoriaGabriela]
    name = "Vitoria-Gabriela"
    class = "city"
    x = 3484
    y = 4384
    zoom_level = 1
    description = ""
    link = ""
    from = 2
[Trotenedo]
    name = "Troteñedo"
    class = "city"
    x = 3517
    y = 4169
    zoom_level = 1
    description = ""
    link = ""
    from = 2
