[Hayris]
    name = "Hayris"
    class ="pre-war-capital"
    x = 3680
    y = 3250
    zoom_level = 0
    description = "Known formerly as the city of light, it used to be one of the most famous cities in the world."
    link = ""
    from = 2
[Neighon]
    name = "Neighon"
    class = "city"
    x = 3747
    y = 3137
    zoom_level = 1
    description = ""
    link = ""
    from = 2
[Hondeaux]
    name = "Hondeaux"
    class = "city"
    x = 3654
    y = 3089
    zoom_level = 1
    description = ""
    link = ""
    from = 2
[Fille]
    name = "Fille"
    class = "city"
    x = 3615
    y = 3260
    zoom_level = 1
    description = ""
    link = ""
    from = 2
[Fancee]
    name = "Fancee"
    class = "city"
    x = 3528
    y = 3112
    zoom_level = 1
    description = "A former large city that featured the most amount of crystal ponies outside of the Crystal Empire, it as well was a crystal city. It is surrounded by a cloud of darkness that kills whomever wanders into it, making the city sealed from the wasteland more or less."
    link = ""
    from = 2
[Trotluise]
    name = "Trotluise"
    class = "city"
    x = 3543
    y = 2946
    zoom_level = 1
    description = ""
    link = ""
    from = 2
[Maneille]
    name = "Maneille"
    class = "city"
    x = 3644
    y = 2961
    zoom_level = 1
    description = ""
    link = ""
    from = 2
[Chicacolt]
    name = "Chicacolt"
    class = "city"
    x = 3597
    y = 2860
    zoom_level = 1
    description = "A former booming metropolis that was more equestrian than prench."
    link = "https://falloutequestria.fandom.com/wiki/Chicacolt_(Starlight)"
    from = 3
[Albamareal]
    name = "Albamareal"
    class = "city"
    x = 3531.5
    y = 3235
    zoom_level = 1
    description = ""
    link = ""
    from = 13
[Bridlewood]
    name = "Bridlewood"
    class = "city"
    x = 3551.125 
    y = 3175.125
    zoom_level = 1
    description = "And old pre-war town now the home to a covenant of racially inclined Unicorns that will, sometimes, take in non-Unicorns to their walled in town."
    link = ""
    from = 13
[VilleLacustre]
    name = "Ville Lacustre"
    class = "city"
    x = 3628.75
    y = 3172.40625
    zoom_level = 1
    description = ""
    link = ""
    from = 14
