[Ryakhoof]
    name = "Ryakhoof"
    class ="pre-war-capital"
    x = 2864
    y = 2474
    zoom_level = 0
    description = ""
    link = ""
    from = 2
[Stemphis]
    name = "Stemphis"
    class = "city"
    x = 2946
    y = 2546
    zoom_level = 1
    description = ""
    link = ""
    from = 2