[Roam]
    name = "Roam"
    class ="pre-war-capital"
    x = 3085
    y = 2021
    zoom_level = 0
    description = "The beautyful capital of the zebras now reduced to an eternally burning hell."
    link = ""
    from = 7
[Clavenas]
    name = "Clavenas"
    class = "city"
    x = 3152
    y = 2255
    zoom_level = 1
    description = ""
    link = ""
    from = 2
[Ormoeas]
    name = "Órmoeas"
    class = "city"
    x = 3060
    y = 2162
    zoom_level = 1
    description = ""
    link = ""
    from = 2
[Knochaitios]
    name = "Knochaítios"
    class = "city"
    x = 3020
    y = 2105
    zoom_level = 1
    description = ""
    link = ""
    from = 2
[Alagovala]
    name = "Alagovala"
    class = "city"
    x = 2990
    y = 2037
    zoom_level = 1
    description = ""
    link = ""
    from = 2
[Doryarta]
    name = "Doryarta"
    class = "city"
    x = 3006
    y = 2232
    zoom_level = 1
    description = ""
    link = ""
    from = 2
[Tripodimiki]
    name = "Tripodimiki"
    class = "city"
    x = 3083
    y = 2392
    zoom_level = 1
    description = ""
    link = ""
    from = 2
[Sanctvm]
    name = "Sanctvm"
    class = "city"
    x = 3184
    y = 2412
    zoom_level = 1
    description = "Also known as 'Sanctuary'"
    link = ""
    from = 7
[Zestrvm]
    name = "Zestrvm"
    class = "city"
    x = 3069
    y = 2429
    zoom_level = 1
    description = ""
    link = ""
    from = 2
[Exilivrbs]
    name = "Exilivrbs"
    class = "city"
    x = 3155
    y = 3738
    zoom_level = 1
    description = ""
    link = ""
    from = 2
[Herazevraion]
    name = "Herazévraion"
    class = "city"
    x = 3143
    y = 2177
    zoom_level = 1
    description = ""
    link = ""
    from = 2
[Opliolis]
    name = "Opliolis"
    class = "city"
    x = 3277
    y = 2142
    zoom_level = 1
    description = ""
    link = ""
    from = 2
[OryzaFlvvivs]
    name = "Oryza Flvvivs"
    class = "city"
    x = 3424
    y = 2056
    zoom_level = 1
    description = "Also known as 'Rice River'."
    link = ""
    from = 7
[Thermopolis]
    name = "Thermopolis"
    class = "city"
    x = 3282
    y = 1984
    zoom_level = 1
    description = ""
    link = ""
    from = 2
[Nicomedivm]
    name = "Nicomedivm"
    class = "city"
    x = 3340
    y = 1905
    zoom_level = 1
    description = ""
    link = ""
    from = 2
[Aricornvm]
    name = "Aricornvm"
    class = "city"
    x = 3370
    y = 1837
    zoom_level = 1
    description = ""
    link = ""
    from = 2
[Vallvum]
    name = "Vallvm"
    class = "city"
    x = 3307
    y = 1752
    zoom_level = 1
    description = "Also known as 'Bastion'"
    link = ""
    from = 7
[Lvghinnitvm]
    name = "Lvghinnitvm"
    class = "city"
    x = 3181
    y = 1842
    zoom_level = 1
    description = ""
    link = ""
    from = 2
[Lvmenopolis]
    name = "Lvmenopolis"
    class = "city"
    x = 3025
    y = 1893
    zoom_level = 1
    description = ""
    link = ""
    from = 2
[Zevran]
    name = "Zévran"
    class = "city"
    x = 3185
    y = 1676
    zoom_level = 1
    description = ""
    link = ""
    from = 2
[Londvngvlam]
    name = "Londvgvlam"
    class = "city"
    x = 3442
    y = 1690
    zoom_level = 1
    description = ""
    link = ""
    from = 2
[Rvptvpiclaven]
    name = "Rvptvpiclaven"
    class = "city"
    x = 3591
    y = 1705
    zoom_level = 1
    description = ""
    link = ""
    from = 2
[Blesfrigvs]
    name = "Blesfrigvs"
    class = "city"
    x = 3624 
    y = 1640
    zoom_level = 1
    description = ""
    link = ""
    from = 2
[Glaceniam]
    name = "Glaceniam"
    class = "city"
    x = 3843
    y = 1638
    zoom_level = 1
    description = ""
    link = ""
    from = 2
[Antizevran]
    name = "Antizévran"
    class = "city"
    x = 3447
    y = 1332
    zoom_level = 1
    description = ""
    link = ""
    from = 2
[Hvmidvmia]
    name = "Hvmidvmia"
    class = "city"
    x = 3500
    y = 1292
    zoom_level = 1
    description = ""
    link = ""
    from = 2
[NovvsReginam]
    name = "Novvs Reginam"
    class = "city"
    x = 3474
    y = 1245
    zoom_level = 1
    description = ""
    link = ""
    from = 2
[Marepropem]
    name = "Marepropem"
    class = "city"
    x = 3450
    y = 1060
    zoom_level = 1
    description = ""
    link = ""
    from = 2
[VngvlaSerdica]
    name = "Vngvla Serdica"
    class = "city"
    x = 3500
    y = 1013
    zoom_level = 1
    description = ""
    link = ""
    from = 2
[Caeseratrix]
    name = "Caeseratrix"
    class = "city"
    x = 3579
    y = 1002
    zoom_level = 1
    description = ""
    link = ""
    from = 2
[NovaRoam]
    name = "Nova Roam"
    class = "city"
    x = 3715
    y = 868
    zoom_level = 1
    description = ""
    link = ""
    from = 2
[Rhofias]
    name = "Rhofias"
    class = "city"
    x = 2955 
    y = 2071
    zoom_level = 1
    description = ""
    link = ""
    from = 2
[Canalogos]
    name = "Çanálogos"
    class = "city"
    x = 2924
    y = 2063
    zoom_level = 1
    description = ""
    link = ""
    from = 2
[Trochaitas]
    name = "Trochaítas"
    class = "city"
    x = 2954
    y = 1972
    zoom_level = 1
    description = ""
    link = ""
    from = 2
[Knosto]
    name = "Knósto"
    class = "city"
    x = 2880
    y = 1961
    zoom_level = 1
    description = ""
    link = ""
    from = 2
[Zevrymno]
    name = "Zevrymno"
    class = "city"
    x = 2863
    y = 2015
    zoom_level = 1
    description = ""
    link = ""
    from = 2
[Zakropolis]
    name = "Zakropolis"
    class = "city"
    x = 2855
    y = 2074
    zoom_level = 1
    description = ""
    link = ""
    from = 2
[Mikitainia]
    name = "Mikitainía"
    class = "city"
    x = 2896
    y = 2161
    zoom_level = 1
    description = ""
    link = ""
    from = 2
[Phaignostos]
    name = "Phaignóstos"
    class = "city"
    x = 2839
    y = 2046
    zoom_level = 1
    description = ""
    link = ""
    from = 2
[Maliphilias]
    name = "Maliphilias"
    class = "city"
    x = 2803
    y = 2124
    zoom_level = 1
    description = ""
    link = ""
    from = 2
[Palekalogos]
    name = "Palekálogos"
    class = "city"
    x = 2759
    y = 2061
    zoom_level = 1
    description = ""
    link = ""
    from = 2
[Tylichivos]
    name = "Tylichívos"
    class = "city"
    x = 2728
    y = 2122
    zoom_level = 1
    description = ""
    link = ""
    from = 2
[Calvis]
    name = "Calvis"
    class = "city"
    x = 2752
    y = 1948
    zoom_level = 1
    description = ""
    link = ""
    from = 2
[Cognitionia]
    name = "Cognitionia"
    class = "city"
    x = 2783
    y = 1949
    zoom_level = 1
    description = ""
    link = ""
    from = 2
[Insvlermo]
    name = "Insvlermo"
    class = "city"
    x = 2792
    y = 1913
    zoom_level = 1
    description = ""
    link = ""
    from = 2
[Cagliarem]
    name = "Cagliarem"
    class = "city"
    x = 2832
    y = 1802
    zoom_level = 1
    description = ""
    link = ""
    from = 2
[Pomperlona]
    name = "Pomperlona"
    class = "city"
    x = 2853
    y = 1678
    zoom_level = 1
    description = ""
    link = ""
    from = 2
[Syraecvvs]
    name = "Syræcvvs"
    class = "city"
    x = 2819
    y = 1997
    zoom_level = 1
    description = ""
    link = ""
    from = 2
[Saltvrbs]
    name = "Saltvrbs"
    class = "city"
    x = 2924
    y = 1577
    zoom_level = 1
    description = ""
    link = ""
    from = 2
[NeaBorealia]
    name = "Nea Borealia"
    class = "city"
    x = 3136.25
    y = 3781.59375
    zoom_level = 1
    description = ""
    link = ""
    from = 2
