[Trottingham]
    name = "Trottingham"
    class ="pre-war-capital"
    x = 3357
    y = 3705
    zoom_level = 0
    description = ""
    link = ""
    from = 1
[Poniborg]
    name = "Poniborg"
    class = "city"
    x = 3265
    y = 3674
    zoom_level = 1
    description = ""
    link = ""
    from = 2
[Trotsyvil]
    name = "Trotsyvil"
    class = "city"
    x = 3230
    y = 3625
    zoom_level = 1
    description = ""
    link = ""
    from = 2
[Irktrotsky]
    name = "Irktrotsky"
    class = "city"
    x = 3320
    y = 3616
    zoom_level = 1
    description = ""
    link = ""
    from = 2
[Kopytograd]
    name = "Kopytograd"
    class = "city"
    x = 3311
    y = 3679
    zoom_level = 1
    description = ""
    link = ""
    from = 2
