[Trottingham]
    name = "Trottingham"
    class ="pre-war-capital"
    lat = 3357
    lng = 3705
    zoom_level = 0
    description = ""
    link = ""
    from = 1
[Poniborg]
    name = "Poniborg"
    class = "city"
    lat = 3265
    lng = 3674
    zoom_level = 1
    description = ""
    link = ""
    from = 2
[Trotsyvil]
    name = "Trotsyvil"
    class = "city"
    lat = 3230
    lng = 3625
    zoom_level = 1
    description = ""
    link = ""
    from = 2
[Irktrotsky]
    name = "Irktrotsky"
    class = "city"
    lat = 3320
    lng = 3616
    zoom_level = 1
    description = ""
    link = ""
    from = 2
[Kopytograd]
    name = "Kopytograd"
    class = "city"
    lat = 3311
    lng = 3679
    zoom_level = 1
    description = ""
    link = ""
    from = 2
