[PATH]
    terrain_legend = "./legends/terrain.html"
    poi_list = [
        "pre-war/equestria",
        "post-war/equestria/crownlands-settlements",
        "post-war/equestria/crownlands-locations",
        "post-war/equestria/hoof-settlements",
        "post-war/equestria/hoof-locations",
        "post-war/equestria/frontier-settlements",
        "post-war/equestria/frontier-locations",
        "post-war/equestria/midrust-settlements",
        "post-war/equestria/midrust-locations",
        "pre-war/caledonia",
        "post-war/caledonia/maretoba-settlements",
        "post-war/caledonia/trontario-settlements",
        "post-war/caledonia/trontario-locations",
        "post-war/caledonia/newparadiseandgallopador-settlements",
        "post-war/caledonia/newparadiseandgallopador-locations",
        "pre-war/crystalempire",
        "post-war/crystalempire/crystalempire-settlements",
        "post-war/crystalempire/crystalempire-locations",
        "pre-war/prance",
        "post-war/prance/trottanie-settlements",
        "post-war/prance/trottanie-locations",
        "post-war/prance/seinesia-settlements",
        "post-war/prance/seinesia-locations",
        "pre-war/YAK",
        "pre-war/arya",
        "pre-war/trottingham",
        "post-war/trottingham/trottingham-settlements",
        "pre-war/cervidas",
        "pre-war/griffiedra",
        "post-war/griffiedra/patalonia-locations",
        "post-war/griffiedra/patalonia-settlements",
        "post-war/griffiedra/griffiedra-settlements",
        "pre-war/saddle-arabia",
        "pre-war/abyssinia",
        "pre-war/stormora",
        "pre-war/ezpassion",
        "post-war/ezpassion/ezthalesia-settlements",
        "post-war/ezpassion/ezthalesia-locations",
        "post-war/ezpassion/algalopas-settlements",
        "post-war/ezpassion/algalopas-locations",
        "post-war/ezpassion/thael-e-coen-settlements",
        "post-war/ezpassion/sunkenem-settlements",
        "post-war/ezpassion/magna-starya-settlements",
        "post-war/ezpassion/magna-starya-locations",
        "post-war/ezpassion/passionia-settlements",
        "post-war/ezpassion/extremalistra-settlements",
        "pre-war/spqr",
        "pre-war/grande-rabonia",
        "pre-war/vimtever",
        "pre-war/pratenia",
        "pre-war/champisuyu",
        "pre-war/ausil",
        "post-war/ausil/porto-capital-locations",
        "pre-war/ponska",
        "post-war/ponska/ponska-settlements",
    ]
    poi_legend = "./legends/locations.html"
    features_list = [
        "equestriana",
        "alsahra",
        "antransarctica",
        "griffonia",
        "thermonia",
        "cervinia",
    ]
    features_legend = "./legends/features.html"
    rivers_list = [
        "equestriana",
    ]
    lines_layers = [
        "Roads", #0
        "Railroads", #1
        #"Dirt Roads", #2
    ]
    lines_list = [
        "roads/crownlands",
        "roads/frontier",
        "roads/hoof",
    ]
    lines_legends = [
        "./legends/roads.html",
        "./legends/railroads.html",
    ]
    atribution_list = [
        "<a href='https://www.fimfiction.net/story/119190/fallout-equestria'>Fallout: Equestria</a>", #0
        "My Little Pony G4", #1
        "Fallout Equestria: Serenity", #2
        "<a href='https://www.fimfiction.net/story/17890/fallout-equestria-starlight'>Fallout Equestria: Starlight</a>", #3
        "<a href='https://www.fimfiction.net/story/350442/fallout-equestria-falling-shadows'>Fallout Equestria: Falling Shadows</a>", #4
        "<a href='https://www.fimfiction.net/story/208056/fallout-equestria-project-horizons'>Fallout: Equestria - Project Horizons</a>", #5
        "<a href='https://www.fimfiction.net/story/360410/fallout-equestria-project-horizons-speak'>Fallout Equestria: Project Horizons - Speaks</a>", #6
        "<a href='https://www.fimfiction.net/story/298834/fallout-equestria-homelands'>Fallout Equestria: Homelands</a>", #7
        "<a href='https://www.fimfiction.net/story/662/fallout-equestria-heroes'>Fallout Equestria: Heroes</a>", #8
        "<a href='https://www.fimfiction.net/story/363291/fallout-equestria-dead-end'>Fallout Equestria: Dead End</a>", #9
        "Fallout Equestria: Buckhaven", #10
        "Fallout Equestria: Griffonia", #11
        "<a href='https://steamcommunity.com/sharedfiles/filedetails/?id=1826643372'>Equestria At War</a>", #12
        "<a href='https://www.fimfiction.net/story/514028/fallout-equestria-storm-protocol'>Fallout Equestria: Storm Protocol</a>", #13
        "Fallout Equestria: Vive La Prance", #14
    ]
[CONFIG]
    enable_party_indicator = true #Wether or not the draggable party indicator is enabled
    default_party_indicator = [ #Default position for the party indicator
        3256, #X
        3301 #Y
    ] #To save its new position click on it, it will open a save as window, DO NOT rename the file
    #and save it on the root of the html map(WHERE index.html IS) upon a reload its position should be
    #saved, this is quite clunky, but it'll do for now
    enable_party_indicator_save_on_drag = true #If enabled the save as window will appear after dragging the
    #indicator instead of requiring a click
    map_size = [ #Size of the terrain.webp file, note that ALL LAYERS must have the same aspect ratio
        5120,
        9728
    ]
    enable_leaflet_scalebar = false #Wether or not Leaflet's default scale bar will be visible
    enable_better_scalebar = true #Wether or not Betterscale's scale bar will be visible
    enable_globe = true #Wether or not the Cesium Globe is enabled
    julian_first_day = 2478938.50000 #Min/max values for the day/night slider in Julian Days
    julian_last_day = 2479303.49999 #Make sure to setup a time.toml file!
[poi_colour_list] 
    settlement = [ "255", "0", "0" ]
    city = [ "0", "255", "0" ]
    pre-war-capital = [ "0", "180", "0" ]
    post-war-capital = [ "180", "0", "0" ]
    intra-settlement = [ "0", "180", "180" ]
    misc-poi = [ "0", "255", "255" ]
[features_colour_list]
    natural = [ "255", "255", "0" ]
    unnatural = [ "255", "69", "0" ]
    sea = [ "0", "153", "255" ]