[PATH]
    poi_list = [
        "pre-war/equestria",
        "post-war/equestria/crownlands-settlements",
        "post-war/equestria/crownlands-locations",
        "post-war/equestria/hoof-settlements",
        "post-war/equestria/hoof-locations",
        "post-war/equestria/frontier-settlements",
        "post-war/equestria/frontier-locations",
        "post-war/equestria/midrust-settlements",
        "post-war/equestria/midrust-locations",
        "pre-war/caledonia",
        "post-war/caledonia/maretoba-settlements",
        "post-war/caledonia/trontario-settlements",
        "post-war/caledonia/trontario-locations",
        "post-war/caledonia/newparadiseandgallopador-settlements",
        "post-war/caledonia/newparadiseandgallopador-locations",
        "pre-war/crystalempire",
        "post-war/crystalempire/crystalempire-settlements",
        "post-war/crystalempire/crystalempire-locations",
        "pre-war/prance",
        "post-war/prance/trottanie-settlements",
        "post-war/prance/trottanie-locations",
        "post-war/prance/seinesia-settlements",
        "post-war/prance/seinesia-locations",
        "pre-war/YAK",
        "pre-war/arya",
        "pre-war/trottingham",
        "post-war/trottingham/trottingham-settlements",
        "pre-war/cervidas",
        "pre-war/griffiedra",
        "post-war/griffiedra/patalonia-locations",
        "post-war/griffiedra/patalonia-settlements",
        "pre-war/saddle-arabia",
        "pre-war/abyssinia",
        "pre-war/stormora",
        "pre-war/ezpassion",
        "post-war/ezpassion/ezthalesia-settlements",
        "post-war/ezpassion/ezthalesia-locations",
        "post-war/ezpassion/algalopas-settlements",
        "post-war/ezpassion/algalopas-locations",
        "post-war/ezpassion/thael-e-coen-settlements",
        "post-war/ezpassion/sunkenem-settlements",
        "post-war/ezpassion/magna-starya-settlements",
        "post-war/ezpassion/magna-starya-locations",
        "post-war/ezpassion/passionia-settlements",
        "post-war/ezpassion/extremalistra-settlements",
        "pre-war/spqr",
        "pre-war/grande-rabonia",
        "pre-war/vimtever",
        "pre-war/pratenia",
        "pre-war/champisuyu",
        "pre-war/ausil",
        "post-war/ausil/porto-capital-locations",
    ]
    features_list = [
        "equestriana",
        "alsahra",
        "antransarctica",
        "griffonia",
        "thermonia",
        "cervinia",
    ]
    atribution_list = [
        "<a href='https://www.fimfiction.net/story/119190/fallout-equestria'>Fallout: Equestria</a>", #0
        "My Little Pony G4", #1
        "Fallout Equestria: Project Serenity", #2
        "<a href='https://www.fimfiction.net/story/17890/fallout-equestria-starlight'>Fallout Equestria: Starlight</a>", #3
        "<a href='https://www.fimfiction.net/story/350442/fallout-equestria-falling-shadows'>Fallout Equestria: Falling Shadows</a>", #4
        "<a href='https://www.fimfiction.net/story/208056/fallout-equestria-project-horizons'>Fallout: Equestria - Project Horizons</a>", #5
        "<a href='https://www.fimfiction.net/story/360410/fallout-equestria-project-horizons-speak'>Fallout Equestria: Project Horizons - Speaks</a>", #6
        "<a href='https://www.fimfiction.net/story/298834/fallout-equestria-homelands'>Fallout Equestria: Homelands</a>", #7
        "<a href='https://www.fimfiction.net/story/662/fallout-equestria-heroes'>Fallout Equestria: Heroes</a>", #8
        "<a href='https://www.fimfiction.net/story/363291/fallout-equestria-dead-end'>Fallout Equestria: Dead End</a>", #9
        "Fallout Equestria: Buckhaven", #10
        "Fallout Equestria: Griffonia", #11
        "<a href='https://steamcommunity.com/sharedfiles/filedetails/?id=1826643372'>Equestria At War</a>", #12
    ]
[CONFIG]
    enable_party_indicator = true #Wether or not the draggable party indicator is enabled
    default_party_indicator = [ #Default position for the party indicator
        3256, #Lat
        3301 #Lng
    ] #To save its new position click on it, it will open a save as window, DO NOT rename the file
    #and save it on the root of the html map(WHERE index.html IS) upon a reload its position should be
    #saved, this is quite clunky, but it'll do for now
    enable_party_indicator_save_on_drag = true #If enabled the save as window will appear after dragging the
    #indicator instead of requiring a click
    map_size = [ #Size of the terrain.webp file, note that ALL LAYERS must have this same resolution
        5120,
        9728
    ]
