[Stable102]
    name = "Stable 102"
    class = "misc-poi"
    lat = 3705
    lng = 3941
    zoom_level = 2
    description = ""
    link = ""
    from = 8
[Stable123]
    name = "Stable 123"
    class = "misc-poi"
    lat = 3767
    lng = 3938
    zoom_level = 2
    description = ""
    link = ""
    from = 8
[EAMSStation3]
    name = "E.A.M.S. Station 3"
    class = "intra-settlement"
    lat = 3723
    lng = 3924
    zoom_level = 2
    description = ""
    link = ""
    from = 8
[TheGreatWarMuseum]
    name = "The Great War Museum"
    class = "intra-settlement"
    lat = 3696
    lng = 3952
    zoom_level = 2
    description = "A grand war museum with several originals, including boats!"
    link = ""
    from = 2
[PlatinumsUndergroundOrphanage]
    name = "Platinum's Underground Orphanage"
    class = "intra-settlement"
    lat = 3730
    lng = 3977
    zoom_level = 3
    description = "A secret underground orphanage created by an alicorn called Platinum Haze."
    link = ""
    from = 8
[DiseFlightAcademy]
    name = "Dise Flight Academy"
    class = "intra-settlement"
    lat = 3736
    lng = 3975
    zoom_level = 3
    description = "The home base of the enclave remnants of Caledonia."
    link = ""
    from = 8
[NCAEmbassy]
    name = "NCA Embassy"
    class = "intra-settlement"
    lat = 3737
    lng = 3978
    zoom_level = 3
    description = "The embassy of New Caledonia Alliance."
    link = ""
    from = 8
[PhotoFinishsStudio]
    name = "Photo Finish's Studio"
    class = "intra-settlement"
    lat = 3727
    lng = 3985
    zoom_level = 3
    description = "The H.Q. of The Finishers"
    link = ""
    from = 8
[TheBlackSalamander]
    name = "The Black Salamander"
    class = "intra-settlement"
    lat = 3732 
    lng = 3981
    zoom_level = 3
    description = "Mr. House's casino and base of operations for his <a hrf='https://falloutequestria.fandom.com/wiki/Hizais_(Heroes)'>Hizais</a>."
    link = ""
    from = 8
[TheMoonCasino]
    name = "The Moon Casino"
    class = "intra-settlement"
    lat = 3735
    lng = 3980
    zoom_level = 3
    description = "Roy Mustang's casino and H.Q. of The Mustangs."
    link = ""
    from = 8
[ClipsnClopsCasino]
    name = "Clips & Clops Casino"
    class = "intra-settlement"
    lat = 3733
    lng = 3983
    zoom_level = 3
    description = "The most mysterious of the casionos, owned by Granny Dynamite and her Galicians and also from where the Securiponies are controlled."
    link = ""
    from = 8
[TheAlehouse]
    name = "The Alehouse"
    class = "intra-settlement"
    lat = 3734
    lng = 3979
    zoom_level = 3
    description = "Molly's casino, featuring a gladiatorial arena and the base for her gang: The Baises."
    link = ""
    from = 8
[DiseCrater]
    name = "Dise Crater"
    class = "misc-poi"
    lat = 3740
    lng = 3952
    zoom_level = 2
    description = "The impact site of the megaspell that hit Dise"
    link = ""
    from = 8
