[Stable102]
    name = "Stable 102"
    class = "misc-poi stable"
    x = 3705
    y = 3941
    zoom_level = 2
    description = ""
    link = ""
    from = 8
[Stable123]
    name = "Stable 123"
    class = "misc-poi stable"
    x = 3767
    y = 3938
    zoom_level = 2
    description = ""
    link = ""
    from = 8
[EAMSStation3]
    name = "E.A.M.S. Station 3"
    class = "intra-settlement eams"
    x = 3723
    y = 3924
    zoom_level = 2
    description = ""
    link = ""
    from = 8
[TheGreatWarMuseum]
    name = "The Great War Museum"
    class = "intra-settlement nca"
    x = 3696
    y = 3952
    zoom_level = 2
    description = "A grand war museum with several originals, including boats!"
    link = ""
    from = 2
[DiseFlightAcademy]
    name = "Dise Flight Academy"
    class = "intra-settlement enclave"
    x = 3736
    y = 3975
    zoom_level = 3
    description = "The home base of the enclave remnants of Caledonia."
    link = ""
    from = 8
[NCAEmbassy]
    name = "NCA Embassy"
    class = "intra-settlement nca"
    x = 3737
    y = 3978
    zoom_level = 3
    description = "The embassy of New Caledonia Alliance."
    link = ""
    from = 8
[PhotoFinishsStudio]
    name = "Photo Finish's Studio"
    class = "intra-settlement"
    x = 3727
    y = 3985
    zoom_level = 3
    description = "The H.Q. of The Finishers"
    link = ""
    from = 8
[TheBlackSalamander]
    name = "The Black Salamander"
    class = "intra-settlement casino"
    x = 3732 
    y = 3981
    zoom_level = 3
    description = "Mr. House's casino and base of operations for his <a hrf='https://falloutequestria.fandom.com/wiki/Hizais_(Heroes)'>Hizais</a>."
    link = ""
    from = 8
[TheMoonCasino]
    name = "The Moon Casino"
    class = "intra-settlement casino"
    x = 3735
    y = 3980
    zoom_level = 3
    description = "Roy Mustang's casino and H.Q. of The Mustangs."
    link = ""
    from = 8
[ClipsnClopsCasino]
    name = "Clips & Clops Casino"
    class = "intra-settlement casino"
    x = 3733
    y = 3983
    zoom_level = 3
    description = "The most mysterious of the casionos, owned by Granny Dynamite and her Galicians and also from where the Securiponies are controlled."
    link = ""
    from = 8
[TheAlehouse]
    name = "The Alehouse"
    class = "intra-settlement casino"
    x = 3734
    y = 3979
    zoom_level = 3
    description = "Molly's casino, featuring a gladiatorial arena and the base for her gang: The Baises."
    link = ""
    from = 8
[DiseCrater]
    name = "Dise Crater"
    class = "misc-poi radiation"
    x = 3740
    y = 3952
    zoom_level = 2
    description = "The impact site of the megaspell that hit Dise"
    link = ""
    from = 8
[DiseTunnels]
    name = "Dise Tunnels"
    class = "intra-settlement"
    x = 3728.6875 
    y = 3978
    zoom_level = 1
    description = "A series of underground tunnels under Dise built by Wallkirk as an attempt to create a stable-like bunker system, it failed."
    link = "https://falloutequestria.fandom.com/wiki/Dise_Tunnels_(Heroes)"
    from = 8
