[Marefort]
    name = "Marefort"
    class = "settlement crimsomhoof"
    x = 3766
    y = 3772
    zoom_level = 1
    description = "<a hreff='https://falloutequestria.fandom.com/wiki/Hired_Gun_(Heroes)'>Hired Gun/Silver Storm</a>'s birthplace, a city built onm a fort made entirely of mares."
    link = "https://falloutequestria.fandom.com/wiki/Marefort_(Heroes)"
    from = 8
[Dise]
    name = "Dise"
    class = "settlement"
    x = 3750
    y = 3951
    zoom_level = 1
    description = "The greatest of Caledonia's cities, now one of the most developed places in The Wasteland.<img src='https://static.wikia.nocookie.net/falloutequestria/images/f/fb/Dise.png' style='height: 160px;'></img> Image by: TheOmegaRidley"
    link = "https://falloutequestria.fandom.com/wiki/Dise_(Heroes)"
    from = 8
[Stable42]
    name = "Stable 42"
    class = "post-war-capital stable"
    x = 3749
    y = 3776
    zoom_level = 0
    description = "The center of operations for The <a href='https://falloutequestria.fandom.com/wiki/Crimson_Hoof_(Heroes)'>Crimson Hoof</a>."
    link = ""
    from = 8
[BriddleHope]
    name = "Briddle Hope"
    class = "settlement nca"
    x = 3714 
    y = 3900
    zoom_level = 1
    description = "A small trading settlement that trades a lot with the Dise gangs."
    link = ""
    from = 8
[HellfireBunker]
    name = "Hellfire Bunker"
    class = "settlement steelranger"
    x = 3675
    y = 3923
    zoom_level = 1
    description = "The home base the Dise Steel Rangers Branch.<img src='https://static.wikia.nocookie.net/falloutequestria/images/8/84/Steelrangersfactiondotrook.png' style='height: 160px;'></img> Image by: DotRook"
    link = ""
    from = 8
[Walltrot]
    name = "Walltrot"
    class = "settlement nca"
    x = 3690
    y = 3959
    zoom_level = 1
    description = ""
    link = ""
    from = 2
[DiseStrip]
    name = "Dise Strip"
    class = "settlement"
    x = 3736
    y = 3984
    zoom_level = 1
    description = "The center of wealth of Dise where its famous casinos and major gangs reside."
    link = ""
    from = 8
[ParadiseMound]
    name = "Paradise Mound"
    class = "settlement"
    x = 3724
    y = 3991
    zoom_level = 1
    description = "The periphery of Dise, where lowlifes lives. It is mainly controlled by The Finishers."
    link = ""
    from = 8
[TheBeak]
    name = "The Beak"
    class = "settlement talon"
    x = 3716
    y = 3977
    zoom_level = 1
    description = "The old griffon district of Dise, now home of the Golden Talons company."
    link = ""
    from = 2
[Flankyard]
    name = "Flankyard"
    class = "settlement nca"
    x = 3731
    y = 4011
    zoom_level = 1
    description = ""
    link = ""
    from = 8
[Timber]
    name = "Timber"
    class = "settlement crimsomhoof"
    x = 3716
    y = 3851
    zoom_level = 1
    description = ""
    link = ""
    from = 8
[PlatinumsUndergroundOrphanage]
    name = "Platinum's Underground Orphanage"
    class = "settlement unity"
    x = 3730
    y = 3977
    zoom_level = 3
    description = "A secret underground orphanage created by an alicorn called Platinum Haze."
    link = ""
    from = 8
