[MuseoDeArtesYCienciasDeGrifencia]
    name = "Museo de Artes y Ciencias de Griféncia"
    class = "intra-settlement"
    x = 3289
    y = 4070
    zoom_level = 2
    description = "A magnificent advanced museum, featuring live virtual reality rooms and a plethora of artifacts, said to be extremelly dangerous but filled with valuable loot. Name means: Museum of Arts and Sciences of Grifencia."
    link = ""
    from = 11
[PuertoDeGrifencia]
    name = "Puerto de Griféncia"
    class = "intra-settlement"
    x = 3282
    y = 4066
    zoom_level = 3
    description = "A very active port for the settlement of Bastión. Name means: Grifencia Port."
    link = ""
    from = 11
[FortalezaDorada]
    name = "Fortaleza Dorada"
    class = "intra-settlement"
    x = 3285
    y = 4075
    zoom_level = 3
    description = "The home of the duchess of Bastión. Name means: Golden Fortress."
    link = ""
    from = 11
[LaPataDeOro]
    name = "La Pata de Oro"
    class = "intra-settlement"
    x = 3288
    y = 4067
    zoom_level = 3
    description = "A small but quite popular bar famous for its discounts. Owned by a griffon named Amanda and managed by her daughter Clara. Name means: The Golden Paw."
    link = ""
    from = 11