[Bastion]
    name = "Bastión"
    class = "settlement"
    x = 3286
    y = 4070
    zoom_level = 1
    description = "A bustling settlement along the canal city of Griféncia, lead by a duchess."
    link = ""
    from = 11
