[MuseoDeArtesYCienciasDeGrifencia]
    name = "Museo de Artes y Ciencias de Griféncia"
    class = "intra-settlement"
    x = 3289
    y = 4070
    zoom_level = 2
    description = "A magnificent advanced museum, featuring live virtual reality rooms and a plethora of artifacts, said to be extremelly dangerous but filled with valuable loot. Name means: Museum of Arts and Sciences of Grifencia."
    link = ""
    from = 11
[PuertoDeGrifencia]
    name = "Puerto de Griféncia"
    class = "intra-settlement"
    x = 3282
    y = 4066
    zoom_level = 3
    description = "A very active port for the settlement of Bastión. Name means: Grifencia Port."
    link = ""
    from = 11
[FortalezaDorada]
    name = "Fortaleza Dorada"
    class = "intra-settlement"
    x = 3285
    y = 4075
    zoom_level = 3
    description = "The home of the duchess of Bastión. Name means: Golden Fortress."
    link = ""
    from = 11
[LaPataDeOro]
    name = "La Pata de Oro"
    class = "intra-settlement"
    x = 3288
    y = 4067
    zoom_level = 3
    description = "A small but quite popular bar famous for its discounts. Owned by a griffon named Amanda and managed by her daughter Clara. Name means: The Golden Paw."
    link = ""
    from = 11
[LasTransportadoras]
    name = "Las Transportadoras"
    class = "intra-settlement"
    x = 3285.5078125
    y = 4074.4609375
    zoom_level = 3
    description = "Two large factories where no one is allowed to go. Name means: The Conveyors."
    link = ""
    from = 11
[LaCamaDeSuAlteza]
    name = "La Cama De Su Alteza"
    class = "intra-settlement"
    x = 3286.25
    y = 4075.166015625
    zoom_level = 3
    description = "A large gated aristocratic suburb. Name means: Your Highness' Beds."
    link = ""
    from = 11
[LosBolsillosPesados]
    name = "Los Bolsillos Pesados"
    class = "intra-settlement shop"
    x = 3286.73828125
    y = 4071.3994140625
    zoom_level = 3
    description = "A very large central market filled with just about everything, including a magic shop run by a kirin named Gonzales. Name means: The Heavy Pockets."
    link = ""
    from = 11