[2016WorldsFairCentre]
    name = "2016 World's Fair Centre"
    class = "misc-poi"
    x = 4167
    y = 3920
    zoom_level = 2
    description = "The old site of the 2016 World's Fair, where everyone who wanders never returns."
    link = ""
    from = 2
[EAMSStation4]
    name = "E.A.M.S. Station 4"
    class = "intra-settlement eams"
    x = 4171
    y = 3587
    zoom_level = 2
    description = ""
    link = ""
    from = 2
[CrystalPalace]
    name = "Crystal Palace"
    class = "intra-settlement"
    x = 4180
    y = 3577
    zoom_level = 2
    description = "The old palace of the crystallian royalty."
    link = ""
    from = 1
[Stable-TecLab]
    name = "Stable-Tec Ice Research"
    class = "misc-poi"
    x = 3943.75
    y = 3459.6328125
    zoom_level = 3
    description = "An abandoned lab owned by Stable-Tec."
    link = ""
    from = 17
