[BuffaloDesert]
    name = "Buffalo Desert"
    class = "natural"
    x = 3278
    y = 2943
[SanPalominoDesert]
    name = "San Palomino Desert"
    class = "natural"
    x = 3194
    y = 3094
[Ezpassionia]
    name = "Ezpassionia"
    class = "natural"
    x = 3017
    y = 3013
[GreatAlsahranDesert]
    name = "Great Alsahran Desert"
    class = "natural"
    x = 3136
    y = 2718
[SaddleForest]
    name = "Saddle Forest"
    class = "natural"
    x = 2705
    y = 2752
[WasatIsland]
    name = "Wasat Island"
    class = "natural"
    x = 2683
    y = 2579
[PeakOfThales]
    name = "Peak of Thales"
    class = "natural"
    x = 2997
    y = 2880
[KirinPeaks]
    name = "Kirin Peaks"
    class = "natural"
    x = 2980
    y = 2957
[ThalYCoen]
    name = "Thal Y Coen"
    class = "natural"
    x = 3042
    y = 2932
[NoPonysLAnd]
    name = "No Pony's Land"
    class = "unnatural"
    x = 3263
    y = 2646
[PassionicaForest]
    name = "Passionica Forest"
    class = "unnatural"
    x = 2925
    y = 3026
[LunarChannel]
    name = "Lunar Channel"
    class = "sea"
    x = 2913
    y = 2871
