[EverfreeForest]
    name = "Everfree Forest"
    class = "natural"
    x = 3159
    y = 3323
[MarejaveDesert]
    name = "Marejave Desert"
    class = "natural"
    x = 3225 
    y = 3174
[TheBadlands]
    name = "The Badlands"
    class = "natural"
    x = 3127
    y = 3196
[PineForest]
    name = "Pine Forest"
    class = "natural"
    x = 3526
    y = 3780
[GoldeSandsDesert]
    name = "Golden Sands Desert"
    class = "natural"
    x = 3772  
    y = 4024
[SerenePeaksPark]
    name = "Serene Peaks Park"
    class = "natural"
    x = 3988
    y = 3600
[CaledonianHighlands]
    name = "Caledonian Highlands"
    class = "natural"
    x = 3801
    y = 3698
[Equestrian-prenchRange]
    name = "Equestrian-prench Range"
    class = "natural"
    x = 3479
    y = 3302
[ThestralIsland]
    name = "Thestral Island"
    class = "natural"
    x = 4034
    y = 3118
[QuartzArchipelago]
    name = "Quartz Archipelago"
    class = "natural"
    x = 4157 
    y = 4004
[PrismArchipelago]
    name = "Prism Archipelago"
    class = "natural"
    x = 4310 
    y = 4308
[WhitetailWoods]
    name = "Whitetail Woods"
    class = "natural"
    x = 3308
    y = 3297
[IsleOfTrottingham]
    name = "Isle of Trottingham"
    class = "natural"
    x = 3247  
    y = 3712
[AppleachianMountains]
    name = "Appleachian Mountains"
    class = "natural"
    x = 3550.125 
    y = 3277
[LePassage]
    name = "Le Passage"
    class = "natural"
    x = 3425
    y = 3131.140625
[HautesterresdeSombral]
    name = "Hautes-terres de Sombral"
    class = "natural"
    x = 3529.375
    y = 3027.53125
[SplendidValley]
    name = "Splendid Valley"
    class = "unnatural"
    x = 3250
    y = 3248
[RedForest]
    name = "Red Forest"
    class = "unnatural"
    x = 3850
    y = 3559
[PinewoodsPark]
    name = "Pinewoods Park"
    class = "unnatural"
    x = 3571
    y = 3609
[TheExclusionZone]
    name = "The Exclusion Zone"
    class = "unnatural"
    x = 3280
    y = 3619
[NorthwoodsWasteland]
    name = "Northwoods Wasteland"
    class = "unnatural"
    x = 3420
    y = 3039
[HoofBay]
    name = "Hoof Bay"
    class = "sea"
    x = 3378
    y = 3641
[CelestialChannel]
    name = "Celestial Channel"
    class = "sea"
    x = 3312
    y = 3058
[TheGreatTradeBay]
    name = "The Great Trade Bay"
    class = "sea"
    x = 3563
    y = 3996
[ManeBay]
    name = "Mane Bay"
    class = "sea"
    x = 3267
    y = 3456
[SplendidLake]
    name = "Splendid Lake"
    class = "sea"
    x = 3385
    y = 3351
[SeineLake]
    name = "Seine Lake"
    class = "sea"
    x = 3714 
    y = 3202
[HeartBay]
    name = "Heart Bay"
    class = "sea"
    x = 3883
    y = 3475
