[PatapicoDesert]
    name = "Patapico Desert"
    class = "natural"
    x = 3367
    y = 4253
[PatriaGriffia]
    name = "Patria Griffia"
    class = "natural"
    x = 3223
    y = 4345
[LakeTipata]
    name = "Lake Tipata"
    class = "sea"
    x = 3216
    y = 4176