[ImanisMagnis]
    name = "Imanis Magnis"
    class = "natural"
    x = 3235
    y = 1861
[ExoterikosForest]
    name = "Exoterikos Forest"
    class = "natural"
    x = 3094
    y = 2353
[MegalooidsForest]
    name = "Megaloids Forest"
    class = "natural"
    x = 3137 
    y = 2127
[SofiaHighlands]
    name = "Sofia Highlands"
    class = "natural"
    x = 3181
    y = 2287
[LumenForest]
    name = "Lumen Forest"
    class = "natural"
    x = 2952
    y = 1845
[AigalogosArchpelago]
    name = "Aigalogos Archipelago"
    class = "natural"
    x = 2853
    y = 1938
[RoamanBay]
    name = "Roaman Bay"
    class = "sea"
    x = 3034
    y = 1944
[ZevraBay]
    name = "Zevra Bay"
    class = "sea"
    x = 3003
    y = 2163
[DiairesteChannel]
    name = "Diaireste Channel"
    class = "sea"
    x = 2987 
    y = 2279