[PalacioDaInquisicao]
    name = "Palácio da Inquisição"
    class = "intra-settlement"
    x = 2211
    y = 2916
    zoom_level = 3
    description = "The Palace of the Inquisition, one of the oldest buildings in Porto Capital. It houses Ausil's main inquisitorial court"
    link = ""
    from = 2
[PalacioDaJustica]
    name = "Palácio da Justiça"
    class = "intra-settlement"
    x = 2210
    y = 2918
    zoom_level = 3
    description = "The Justice Palace, a colonial era building that houses various courtrooms and high justice officials."
    link = ""
    from = 2
[PalacioDaAuvorada]
    name = "Palácio da Auvorada"
    class = "intra-settlement"
    x = 2213
    y = 2921
    zoom_level = 3
    description = "The Presidential Palace of Ausil."
    link = ""
    from = 2
[CongressoNacional]
    name = "Congresso Nacional"
    class = "intra-settlement"
    x = 2212
    y = 2914
    zoom_level = 3
    description = "The National Congress, where both houses of parliament are located."
    link = ""
    from = 2
[MinisterioDeDefesaPublica]
    name = "Ministério de Defesa Pública"
    class = "intra-settlement"
    x = 2209
    y = 2917
    zoom_level = 3
    description = "The Ministry of Public Defense's building, it houses the Minister herself and various other offices."
    link = ""
    from = 2
[EmbaixadaEquestriana]
    name = "Embaixada Equestriana"
    class = "intra-settlement lodge"
    x = 2205
    y = 2917
    zoom_level = 3
    description = "The old embassy building for the long gone Principality of Equestria."
    link = ""
    from = 2
[PalacioKauane]
    name = "Palácio de Kauane"
    class = "intra-settlement"
    x = 2203
    y = 2921
    zoom_level = 3
    description = "The 'palace' of the old gelupirí monarchy."
    link = ""
    from = 2
[DistritoDeGuarabara]
    name = "Distrito de Guarábara"
    class = "intra-settlement"
    x = 2208
    y = 2916
    zoom_level = 2
    description = "The central administrative district of Ausil, where most federal buildings are located."
    link = ""
    from = 2
[CasteloDasDiretas]
    name = "Castelo Das Diretas"
    class = "intra-settlement"
    x = 2193
    y = 2890
    zoom_level = 2
    description = "The large and ancient castle of the Direta familly. Currently owned by an international prosecutor named Amanda Direta"
    link = ""
    from = 2
[ASenzalaInconfidente]
    name = "A Senzala Inconfidênte"
    class = "intra-settlement"
    x = 2224
    y = 2908
    zoom_level = 2
    description = "An old unassuming unpreserved colonial house that now leads to the H.Q. of the new inconfident revolutionaries."
    link = ""
    from = 2