[PalacioDaInquisicao]
    name = "Palácio da Inquisição"
    class = "intra-settlement"
    lat = 2211
    lng = 2916
    zoom_level = 3
    description = "The Palace of the Inquisition, one of the oldest buildings in Porto Capital. It houses Ausil's main inquisitorial court"
    link = ""
    from = 2
[PalacioDaJustica]
    name = "Palácio da Justiça"
    class = "intra-settlement"
    lat = 2210
    lng = 2918
    zoom_level = 3
    description = "The Justice Palace, a colonial era building that houses various courtrooms and high justice officials."
    link = ""
    from = 2
[PalacioDaAuvorada]
    name = "Palácio da Auvorada"
    class = "intra-settlement"
    lat = 2213
    lng = 2921
    zoom_level = 3
    description = "The Presidential Palace of Ausil."
    link = ""
    from = 2
[CongressoNacional]
    name = "Congresso Nacional"
    class = "intra-settlement"
    lat = 2212
    lng = 2914
    zoom_level = 3
    description = "The National Congress, where both houses of parliament are located."
    link = ""
    from = 2
[MinisterioDeDefesaPublica]
    name = "Ministério de Defesa Pública"
    class = "intra-settlement"
    lat = 2209
    lng = 2917
    zoom_level = 3
    description = "The Ministry of Public Defense's building, it houses the Minister herself and various other offices."
    link = ""
    from = 2
[EmbaixadaEquestriana]
    name = "Embaixada Equestriana"
    class = "intra-settlement"
    lat = 2205
    lng = 2917
    zoom_level = 3
    description = "The old embassy building for the long gone Principality of Equestria."
    link = ""
    from = 2
[PalacioKauane]
    name = "Palácio de Kauane"
    class = "intra-settlement"
    lat = 2203
    lng = 2921
    zoom_level = 3
    description = "The 'palace' of the old gelupirí monarchy."
    link = ""
    from = 2
[DistritoDeGuarabara]
    name = "Distrito de Guarábara"
    class = "intra-settlement"
    lat = 2208
    lng = 2916
    zoom_level = 2
    description = "The central administrative district of Ausil, where most federal buildings are located."
    link = ""
    from = 2
[CasteloDasDiretas]
    name = "Castelo Das Diretas"
    class = "intra-settlement"
    lat = 2193
    lng = 2890
    zoom_level = 2
    description = "The large and ancient castle of the Direta familly."
    link = ""
    from = 2
[ASenzalaInconfidente]
    name = "A Senzala Inconfidênte"
    class = "intra-settlement"
    lat = 2224
    lng = 2908
    zoom_level = 2
    description = "An old unassuming unpreserved colonial house that now leads to the H.Q. of the new inconfident revolutionaries."
    link = ""
    from = 2