[Stalliongrad]
    name = "Stalliongrad"
    class = "post-war-capital sniezhannia"
    x = 3342
    y = 3711
    zoom_level = 0
    description = "The only bustling settlement in trottingham and capital of the Sniezhannia Socialist Soviet Republic."
    link = ""
    from = 12